-- Decompiled using luadec 2.0.1 by sztupy (http://winmo.sztupy.hu)
-- Command line was: F:\SteamLibrary\SteamApps\common\PAYDAY 2\lua\lib\utils\game_state_machine\gamestatemachine.luac 

core:import("CoreGameStateMachine")
require("lib/states/BootupState")
require("lib/states/CreditsState")
require("lib/states/MenuTitlescreenState")
require("lib/states/MenuMainState")
require("lib/states/EditorState")
require("lib/states/WorldCameraState")
require("lib/states/IngamePlayerBase")
require("lib/states/IngameStandard")
require("lib/states/IngameMaskOff")
require("lib/states/IngameBleedOut")
require("lib/states/IngameFatalState")
require("lib/states/IngameWaitingForPlayers")
require("lib/states/IngameWaitingForRespawn")
require("lib/states/IngameArrested")
require("lib/states/IngameElectrified")
require("lib/states/IngameIncapacitated")
require("lib/states/IngameClean")
require("lib/states/MissionEndState")
require("lib/states/VictoryState")
require("lib/states/GameOverState")
require("lib/states/ServerLeftState")
require("lib/states/DisconnectedState")
require("lib/states/KickedState")
require("lib/states/IngameLobbyMenu")
require("lib/states/IngameAccessCamera")
if not GameStateMachine then
  GameStateMachine = class(CoreGameStateMachine.GameStateMachine)
end
GameStateMachine.init = function(l_1_0)
  if not Global.game_state_machine then
    Global.game_state_machine = {is_boot_intro_done = false, is_boot_from_sign_out = false}
  end
  l_1_0._is_boot_intro_done = Global.game_state_machine.is_boot_intro_done
  Global.game_state_machine.is_boot_intro_done = true
  l_1_0._is_boot_from_sign_out = Global.game_state_machine.is_boot_from_sign_out
  Global.game_state_machine.is_boot_from_sign_out = false
  local setup_boot = (not l_1_0._is_boot_intro_done and not Application:editor())
  if setup_boot or l_1_0._is_boot_from_sign_out then
    local setup_title = not Application:editor()
  end
  local states = {}
  local empty = GameState:new("empty", l_1_0)
  local editor = EditorState:new(l_1_0)
  local world_camera = WorldCameraState:new(l_1_0)
  local bootup = BootupState:new(l_1_0, setup_boot)
  local menu_titlescreen = MenuTitlescreenState:new(l_1_0, setup_title)
  local menu_main = MenuMainState:new(l_1_0)
  local ingame_standard = IngameStandardState:new(l_1_0)
  local ingame_mask_off = IngameMaskOffState:new(l_1_0)
  local ingame_bleed_out = IngameBleedOutState:new(l_1_0)
  local ingame_fatal = IngameFatalState:new(l_1_0)
  local ingame_arrested = IngameArrestedState:new(l_1_0)
  local ingame_electrified = IngameElectrifiedState:new(l_1_0)
  local ingame_incapacitated = IngameIncapacitatedState:new(l_1_0)
  local ingame_waiting_for_players = IngameWaitingForPlayersState:new(l_1_0)
  local ingame_waiting_for_respawn = IngameWaitingForRespawnState:new(l_1_0)
  local ingame_clean = IngameCleanState:new(l_1_0)
  local ingame_access_camera = IngameAccessCamera:new(l_1_0)
  local ingame_lobby = IngameLobbyMenuState:new(l_1_0)
  local gameoverscreen = GameOverState:new(l_1_0)
  local server_left = ServerLeftState:new(l_1_0)
  local disconnected = DisconnectedState:new(l_1_0)
  local kicked = KickedState:new(l_1_0)
  local victoryscreen = VictoryState:new(l_1_0)
  local empty_func = callback(nil, empty, "default_transition")
  local editor_func = callback(nil, editor, "default_transition")
  local world_camera_func = callback(nil, world_camera, "default_transition")
  local bootup_func = callback(nil, bootup, "default_transition")
  local menu_titlescreen_func = callback(nil, menu_titlescreen, "default_transition")
  local menu_main_func = callback(nil, menu_main, "default_transition")
  local ingame_standard_func = callback(nil, ingame_standard, "default_transition")
  local ingame_mask_off_func = callback(nil, ingame_mask_off, "default_transition")
  local ingame_bleed_out_func = callback(nil, ingame_bleed_out, "default_transition")
  local ingame_arrested_func = callback(nil, ingame_arrested, "default_transition")
  local ingame_fatal_func = callback(nil, ingame_fatal, "default_transition")
  local ingame_electrified_func = callback(nil, ingame_electrified, "default_transition")
  local ingame_incapacitated_func = callback(nil, ingame_incapacitated, "default_transition")
  local ingame_waiting_for_players_func = callback(nil, ingame_waiting_for_players, "default_transition")
  local ingame_waiting_for_respawn_func = callback(nil, ingame_waiting_for_respawn, "default_transition")
  local ingame_clean_func = callback(nil, ingame_clean, "default_transition")
  local ingame_access_camera_func = callback(nil, ingame_access_camera, "default_transition")
  local ingame_lobby_func = callback(nil, ingame_lobby, "default_transition")
  local gameoverscreen_func = callback(nil, gameoverscreen, "default_transition")
  local server_left_func = callback(nil, server_left, "default_transition")
  local disconnected_func = callback(nil, disconnected, "default_transition")
  local kicked_func = callback(nil, disconnected, "default_transition")
  local victoryscreen_func = callback(nil, victoryscreen, "default_transition")
  l_1_0._controller_enabled_count = 1
  CoreGameStateMachine.GameStateMachine.init(l_1_0, empty)
  l_1_0:add_transition(editor, empty, editor_func)
  l_1_0:add_transition(editor, world_camera, editor_func)
  l_1_0:add_transition(editor, editor, editor_func)
  l_1_0:add_transition(editor, ingame_standard, editor_func)
  l_1_0:add_transition(editor, ingame_mask_off, editor_func)
  l_1_0:add_transition(editor, ingame_bleed_out, editor_func)
  l_1_0:add_transition(editor, ingame_fatal, editor_func)
  l_1_0:add_transition(editor, victoryscreen, editor_func)
  l_1_0:add_transition(editor, ingame_clean, editor_func)
  l_1_0:add_transition(world_camera, editor, world_camera_func)
  l_1_0:add_transition(world_camera, empty, world_camera_func)
  l_1_0:add_transition(world_camera, world_camera, world_camera_func)
  l_1_0:add_transition(world_camera, ingame_standard, world_camera_func)
  l_1_0:add_transition(world_camera, ingame_mask_off, world_camera_func)
  l_1_0:add_transition(world_camera, ingame_bleed_out, world_camera_func)
  l_1_0:add_transition(world_camera, ingame_fatal, world_camera_func)
  l_1_0:add_transition(world_camera, ingame_arrested, world_camera_func)
  l_1_0:add_transition(world_camera, ingame_electrified, world_camera_func)
  l_1_0:add_transition(world_camera, ingame_incapacitated, world_camera_func)
  l_1_0:add_transition(world_camera, ingame_waiting_for_players, world_camera_func)
  l_1_0:add_transition(world_camera, ingame_waiting_for_respawn, world_camera_func)
  l_1_0:add_transition(world_camera, ingame_clean, world_camera_func)
  l_1_0:add_transition(world_camera, server_left, world_camera_func)
  l_1_0:add_transition(world_camera, disconnected, world_camera_func)
  l_1_0:add_transition(world_camera, kicked, world_camera_func)
  l_1_0:add_transition(world_camera, victoryscreen, world_camera)
  l_1_0:add_transition(bootup, menu_titlescreen, bootup_func)
  l_1_0:add_transition(menu_titlescreen, menu_main, menu_titlescreen_func)
  l_1_0:add_transition(ingame_standard, editor, ingame_standard_func)
  l_1_0:add_transition(ingame_standard, world_camera, ingame_standard_func)
  l_1_0:add_transition(ingame_standard, ingame_mask_off, ingame_standard_func)
  l_1_0:add_transition(ingame_standard, ingame_bleed_out, ingame_standard_func)
  l_1_0:add_transition(ingame_standard, ingame_fatal, ingame_standard_func)
  l_1_0:add_transition(ingame_standard, ingame_arrested, ingame_standard_func)
  l_1_0:add_transition(ingame_standard, ingame_electrified, ingame_standard_func)
  l_1_0:add_transition(ingame_standard, ingame_incapacitated, ingame_standard_func)
  l_1_0:add_transition(ingame_standard, victoryscreen, ingame_standard_func)
  l_1_0:add_transition(ingame_standard, ingame_waiting_for_respawn, ingame_standard_func)
  l_1_0:add_transition(ingame_standard, ingame_standard, ingame_standard_func)
  l_1_0:add_transition(ingame_standard, ingame_waiting_for_players, ingame_standard_func)
  l_1_0:add_transition(ingame_standard, ingame_clean, ingame_standard_func)
  l_1_0:add_transition(ingame_standard, ingame_access_camera, ingame_standard_func)
  l_1_0:add_transition(ingame_standard, server_left, ingame_standard_func)
  l_1_0:add_transition(ingame_standard, gameoverscreen, ingame_standard_func)
  l_1_0:add_transition(ingame_standard, disconnected, ingame_standard_func)
  l_1_0:add_transition(ingame_standard, kicked, ingame_standard_func)
  l_1_0:add_transition(ingame_mask_off, editor, ingame_mask_off_func)
  l_1_0:add_transition(ingame_mask_off, world_camera, ingame_mask_off_func)
  l_1_0:add_transition(ingame_mask_off, ingame_standard, ingame_mask_off_func)
  l_1_0:add_transition(ingame_mask_off, ingame_bleed_out, ingame_mask_off_func)
  l_1_0:add_transition(ingame_mask_off, ingame_fatal, ingame_mask_off_func)
  l_1_0:add_transition(ingame_mask_off, ingame_arrested, ingame_mask_off_func)
  l_1_0:add_transition(ingame_mask_off, ingame_electrified, ingame_mask_off_func)
  l_1_0:add_transition(ingame_mask_off, ingame_incapacitated, ingame_mask_off_func)
  l_1_0:add_transition(ingame_mask_off, ingame_waiting_for_respawn, ingame_mask_off_func)
  l_1_0:add_transition(ingame_mask_off, ingame_clean, ingame_mask_off_func)
  l_1_0:add_transition(ingame_mask_off, ingame_access_camera, ingame_mask_off_func)
  l_1_0:add_transition(ingame_mask_off, server_left, ingame_mask_off_func)
  l_1_0:add_transition(ingame_mask_off, victoryscreen, ingame_mask_off_func)
  l_1_0:add_transition(ingame_mask_off, gameoverscreen, ingame_mask_off_func)
  l_1_0:add_transition(ingame_mask_off, disconnected, ingame_mask_off_func)
  l_1_0:add_transition(ingame_mask_off, kicked, ingame_mask_off_func)
  l_1_0:add_transition(ingame_clean, editor, ingame_clean_func)
  l_1_0:add_transition(ingame_clean, world_camera, ingame_clean_func)
  l_1_0:add_transition(ingame_clean, ingame_mask_off, ingame_clean_func)
  l_1_0:add_transition(ingame_clean, ingame_standard, ingame_clean_func)
  l_1_0:add_transition(ingame_clean, ingame_bleed_out, ingame_clean_func)
  l_1_0:add_transition(ingame_clean, ingame_fatal, ingame_clean_func)
  l_1_0:add_transition(ingame_clean, ingame_arrested, ingame_clean_func)
  l_1_0:add_transition(ingame_clean, ingame_electrified, ingame_clean_func)
  l_1_0:add_transition(ingame_clean, ingame_incapacitated, ingame_clean_func)
  l_1_0:add_transition(ingame_clean, ingame_waiting_for_respawn, ingame_clean_func)
  l_1_0:add_transition(ingame_clean, ingame_access_camera, ingame_clean_func)
  l_1_0:add_transition(ingame_clean, server_left, ingame_clean_func)
  l_1_0:add_transition(ingame_clean, gameoverscreen, ingame_clean_func)
  l_1_0:add_transition(ingame_clean, disconnected, ingame_clean_func)
  l_1_0:add_transition(ingame_clean, kicked, ingame_clean_func)
  l_1_0:add_transition(ingame_access_camera, editor, ingame_access_camera_func)
  l_1_0:add_transition(ingame_access_camera, world_camera, ingame_access_camera_func)
  l_1_0:add_transition(ingame_access_camera, ingame_mask_off, ingame_access_camera_func)
  l_1_0:add_transition(ingame_access_camera, ingame_standard, ingame_access_camera_func)
  l_1_0:add_transition(ingame_access_camera, ingame_bleed_out, ingame_access_camera_func)
  l_1_0:add_transition(ingame_access_camera, ingame_fatal, ingame_access_camera_func)
  l_1_0:add_transition(ingame_access_camera, ingame_arrested, ingame_access_camera_func)
  l_1_0:add_transition(ingame_access_camera, ingame_electrified, ingame_access_camera_func)
  l_1_0:add_transition(ingame_access_camera, ingame_incapacitated, ingame_access_camera_func)
  l_1_0:add_transition(ingame_access_camera, server_left, ingame_access_camera_func)
  l_1_0:add_transition(ingame_access_camera, gameoverscreen, ingame_access_camera_func)
  l_1_0:add_transition(ingame_access_camera, disconnected, ingame_access_camera_func)
  l_1_0:add_transition(ingame_access_camera, kicked, ingame_access_camera_func)
  l_1_0:add_transition(ingame_bleed_out, editor, ingame_bleed_out_func)
  l_1_0:add_transition(ingame_bleed_out, world_camera, ingame_bleed_out_func)
  l_1_0:add_transition(ingame_bleed_out, ingame_standard, ingame_bleed_out_func)
  l_1_0:add_transition(ingame_bleed_out, ingame_mask_off, ingame_bleed_out_func)
  l_1_0:add_transition(ingame_bleed_out, ingame_fatal, ingame_bleed_out_func)
  l_1_0:add_transition(ingame_bleed_out, ingame_arrested, ingame_bleed_out_func)
  l_1_0:add_transition(ingame_bleed_out, victoryscreen, ingame_bleed_out_func)
  l_1_0:add_transition(ingame_bleed_out, ingame_waiting_for_respawn, ingame_bleed_out_func)
  l_1_0:add_transition(ingame_bleed_out, gameoverscreen, ingame_bleed_out_func)
  l_1_0:add_transition(ingame_bleed_out, server_left, ingame_bleed_out_func)
  l_1_0:add_transition(ingame_bleed_out, disconnected, ingame_bleed_out_func)
  l_1_0:add_transition(ingame_bleed_out, kicked, ingame_bleed_out_func)
  l_1_0:add_transition(ingame_fatal, editor, ingame_fatal_func)
  l_1_0:add_transition(ingame_fatal, world_camera, ingame_fatal_func)
  l_1_0:add_transition(ingame_fatal, ingame_standard, ingame_fatal_func)
  l_1_0:add_transition(ingame_fatal, ingame_mask_off, ingame_fatal_func)
  l_1_0:add_transition(ingame_fatal, ingame_bleed_out, ingame_fatal_func)
  l_1_0:add_transition(ingame_fatal, victoryscreen, ingame_fatal_func)
  l_1_0:add_transition(ingame_fatal, ingame_waiting_for_respawn, ingame_fatal_func)
  l_1_0:add_transition(ingame_fatal, gameoverscreen, ingame_fatal_func)
  l_1_0:add_transition(ingame_fatal, server_left, ingame_fatal_func)
  l_1_0:add_transition(ingame_fatal, disconnected, ingame_fatal_func)
  l_1_0:add_transition(ingame_fatal, kicked, ingame_fatal_func)
  l_1_0:add_transition(ingame_arrested, editor, ingame_arrested_func)
  l_1_0:add_transition(ingame_arrested, world_camera, ingame_arrested_func)
  l_1_0:add_transition(ingame_arrested, ingame_standard, ingame_arrested_func)
  l_1_0:add_transition(ingame_arrested, victoryscreen, ingame_arrested_func)
  l_1_0:add_transition(ingame_arrested, ingame_waiting_for_respawn, ingame_arrested_func)
  l_1_0:add_transition(ingame_arrested, gameoverscreen, ingame_arrested_func)
  l_1_0:add_transition(ingame_arrested, ingame_bleed_out, ingame_arrested_func)
  l_1_0:add_transition(ingame_arrested, server_left, ingame_arrested_func)
  l_1_0:add_transition(ingame_arrested, disconnected, ingame_arrested_func)
  l_1_0:add_transition(ingame_arrested, kicked, ingame_arrested_func)
  l_1_0:add_transition(ingame_electrified, editor, ingame_electrified_func)
  l_1_0:add_transition(ingame_electrified, world_camera, ingame_electrified_func)
  l_1_0:add_transition(ingame_electrified, ingame_standard, ingame_electrified_func)
  l_1_0:add_transition(ingame_electrified, ingame_incapacitated, ingame_electrified_func)
  l_1_0:add_transition(ingame_electrified, victoryscreen, ingame_electrified_func)
  l_1_0:add_transition(ingame_electrified, ingame_bleed_out, ingame_electrified_func)
  l_1_0:add_transition(ingame_electrified, ingame_fatal, ingame_electrified_func)
  l_1_0:add_transition(ingame_electrified, server_left, ingame_electrified_func)
  l_1_0:add_transition(ingame_electrified, gameoverscreen, ingame_electrified_func)
  l_1_0:add_transition(ingame_electrified, disconnected, ingame_electrified_func)
  l_1_0:add_transition(ingame_electrified, kicked, ingame_electrified_func)
  l_1_0:add_transition(ingame_incapacitated, editor, ingame_incapacitated_func)
  l_1_0:add_transition(ingame_incapacitated, world_camera, ingame_incapacitated_func)
  l_1_0:add_transition(ingame_incapacitated, ingame_standard, ingame_incapacitated_func)
  l_1_0:add_transition(ingame_incapacitated, victoryscreen, ingame_incapacitated_func)
  l_1_0:add_transition(ingame_incapacitated, ingame_waiting_for_respawn, ingame_incapacitated_func)
  l_1_0:add_transition(ingame_incapacitated, gameoverscreen, ingame_incapacitated_func)
  l_1_0:add_transition(ingame_incapacitated, server_left, ingame_incapacitated_func)
  l_1_0:add_transition(ingame_incapacitated, gameoverscreen, ingame_incapacitated_func)
  l_1_0:add_transition(ingame_incapacitated, disconnected, ingame_incapacitated_func)
  l_1_0:add_transition(ingame_incapacitated, kicked, ingame_incapacitated_func)
  l_1_0:add_transition(ingame_waiting_for_players, ingame_standard, ingame_waiting_for_players_func)
  l_1_0:add_transition(ingame_waiting_for_players, ingame_mask_off, ingame_waiting_for_players_func)
  l_1_0:add_transition(ingame_waiting_for_players, ingame_clean, ingame_waiting_for_players_func)
  l_1_0:add_transition(ingame_waiting_for_players, gameoverscreen, ingame_waiting_for_players_func)
  l_1_0:add_transition(ingame_waiting_for_players, victoryscreen, ingame_waiting_for_players_func)
  l_1_0:add_transition(ingame_waiting_for_players, server_left, ingame_waiting_for_players_func)
  l_1_0:add_transition(ingame_waiting_for_players, disconnected, ingame_waiting_for_players_func)
  l_1_0:add_transition(ingame_waiting_for_players, kicked, ingame_waiting_for_players_func)
  l_1_0:add_transition(ingame_waiting_for_players, ingame_lobby, ingame_waiting_for_players_func)
  l_1_0:add_transition(ingame_waiting_for_respawn, ingame_standard, ingame_waiting_for_respawn_func)
  l_1_0:add_transition(ingame_waiting_for_respawn, ingame_mask_off, ingame_waiting_for_respawn_func)
  l_1_0:add_transition(ingame_waiting_for_respawn, editor, ingame_waiting_for_respawn_func)
  l_1_0:add_transition(ingame_waiting_for_respawn, ingame_clean, ingame_waiting_for_respawn_func)
  l_1_0:add_transition(ingame_waiting_for_respawn, gameoverscreen, ingame_waiting_for_respawn_func)
  l_1_0:add_transition(ingame_waiting_for_respawn, victoryscreen, ingame_waiting_for_respawn_func)
  l_1_0:add_transition(ingame_waiting_for_respawn, server_left, ingame_waiting_for_respawn_func)
  l_1_0:add_transition(ingame_waiting_for_respawn, disconnected, ingame_waiting_for_respawn_func)
  l_1_0:add_transition(ingame_waiting_for_respawn, kicked, ingame_waiting_for_respawn_func)
  l_1_0:add_transition(gameoverscreen, gameoverscreen, gameoverscreen_func)
  l_1_0:add_transition(gameoverscreen, editor, gameoverscreen_func)
  l_1_0:add_transition(gameoverscreen, ingame_lobby, gameoverscreen_func)
  l_1_0:add_transition(gameoverscreen, server_left, gameoverscreen_func)
  l_1_0:add_transition(gameoverscreen, disconnected, gameoverscreen_func)
  l_1_0:add_transition(gameoverscreen, kicked, gameoverscreen_func)
  l_1_0:add_transition(gameoverscreen, empty, gameoverscreen_func)
  l_1_0:add_transition(gameoverscreen, menu_main, gameoverscreen_func)
  l_1_0:add_transition(ingame_lobby, empty, ingame_lobby_func)
  l_1_0:add_transition(server_left, ingame_lobby, ingame_lobby_func)
  l_1_0:add_transition(disconnected, ingame_lobby, ingame_lobby_func)
  l_1_0:add_transition(kicked, ingame_lobby, ingame_lobby_func)
  l_1_0:add_transition(server_left, empty, gameoverscreen_func)
  l_1_0:add_transition(server_left, disconnected, gameoverscreen_func)
  l_1_0:add_transition(disconnected, empty, gameoverscreen_func)
  l_1_0:add_transition(kicked, empty, gameoverscreen_func)
  l_1_0:add_transition(victoryscreen, ingame_standard, victoryscreen_func)
  l_1_0:add_transition(victoryscreen, editor, victoryscreen_func)
  l_1_0:add_transition(victoryscreen, ingame_fatal, victoryscreen_func)
  l_1_0:add_transition(victoryscreen, ingame_bleed_out, victoryscreen_func)
  l_1_0:add_transition(victoryscreen, ingame_arrested, victoryscreen_func)
  l_1_0:add_transition(victoryscreen, ingame_electrified, victoryscreen_func)
  l_1_0:add_transition(victoryscreen, world_camera, victoryscreen_func)
  l_1_0:add_transition(victoryscreen, empty, victoryscreen_func)
  l_1_0:add_transition(victoryscreen, ingame_lobby, victoryscreen_func)
  l_1_0:add_transition(victoryscreen, server_left, victoryscreen_func)
  l_1_0:add_transition(victoryscreen, disconnected, victoryscreen_func)
  l_1_0:add_transition(victoryscreen, kicked, victoryscreen_func)
  l_1_0:add_transition(victoryscreen, menu_main, victoryscreen_func)
  l_1_0:add_transition(empty, editor, empty_func)
  l_1_0:add_transition(empty, world_camera, empty_func)
  l_1_0:add_transition(empty, bootup, empty_func)
  l_1_0:add_transition(empty, menu_titlescreen, empty_func)
  l_1_0:add_transition(empty, menu_main, empty_func)
  l_1_0:add_transition(empty, ingame_standard, empty_func)
  l_1_0:add_transition(empty, ingame_mask_off, empty_func)
  l_1_0:add_transition(empty, ingame_bleed_out, empty_func)
  l_1_0:add_transition(empty, ingame_clean, empty_func)
  l_1_0:add_transition(empty, ingame_waiting_for_players, empty_func)
  l_1_0:add_transition(empty, ingame_waiting_for_respawn, empty_func)
  l_1_0:add_transition(empty, gameoverscreen, empty_func)
  l_1_0:add_transition(empty, server_left, empty_func)
  l_1_0:add_transition(empty, victoryscreen, empty_func)
  managers.menu:add_active_changed_callback(callback(l_1_0, l_1_0, "menu_active_changed_callback"))
  managers.system_menu:add_active_changed_callback(callback(l_1_0, l_1_0, "dialog_active_changed_callback"))
end

GameStateMachine.init_finilize = function(l_2_0)
  if managers.hud then
    managers.hud:add_chatinput_changed_callback(callback(l_2_0, l_2_0, "chatinput_changed_callback"))
  end
end

GameStateMachine.set_boot_intro_done = function(l_3_0, l_3_1)
  Global.game_state_machine.is_boot_intro_done = l_3_1
  l_3_0._is_boot_intro_done = l_3_1
end

GameStateMachine.is_boot_intro_done = function(l_4_0)
  return l_4_0._is_boot_intro_done
end

GameStateMachine.set_boot_from_sign_out = function(l_5_0, l_5_1)
  Global.game_state_machine.is_boot_from_sign_out = l_5_1
end

GameStateMachine.is_boot_from_sign_out = function(l_6_0)
  return l_6_0._is_boot_from_sign_out
end

GameStateMachine.menu_active_changed_callback = function(l_7_0, l_7_1)
  l_7_0:_set_controller_enabled(not l_7_1)
end

GameStateMachine.dialog_active_changed_callback = function(l_8_0, l_8_1)
  l_8_0:_set_controller_enabled(not l_8_1)
end

GameStateMachine.chatinput_changed_callback = function(l_9_0, l_9_1)
  l_9_0:_set_controller_enabled(not l_9_1)
end

GameStateMachine.is_controller_enabled = function(l_10_0)
  return l_10_0._controller_enabled_count > 0
end

GameStateMachine._set_controller_enabled = function(l_11_0, l_11_1)
  local was_enabled = l_11_0:is_controller_enabled()
  if l_11_1 then
    l_11_0._controller_enabled_count = l_11_0._controller_enabled_count + 1
  else
    l_11_0._controller_enabled_count = l_11_0._controller_enabled_count - 1
  end
  if not was_enabled ~= not l_11_0:is_controller_enabled() then
    local state = l_11_0:current_state()
    if state then
      state:set_controller_enabled(l_11_1)
    end
  end
end


