-- Decompiled using luadec 2.0.1 by sztupy (http://winmo.sztupy.hu)
-- Command line was: F:\SteamLibrary\SteamApps\common\PAYDAY 2\lua\lib\tweak_data\assetstweakdata.luac 

if not AssetsTweakData then
  AssetsTweakData = class()
end
AssetsTweakData.init = function(l_1_0, l_1_1)
  l_1_0:_init_empty_asset(l_1_1)
  l_1_0:_init_assets(l_1_1)
  l_1_0:_init_risk_assets(l_1_1)
end

AssetsTweakData._init_empty_asset = function(l_2_0, l_2_1)
  l_2_0.none = {}
  l_2_0.none.name_id = nil
  l_2_0.none.unlock_desc_id = nil
  l_2_0.none.texture = nil
  l_2_0.none.stages = nil
  l_2_0.none.require_to_unlock = nil
  l_2_0.none.visible_if_locked = nil
  l_2_0.none.no_mystery = nil
  l_2_0.none.saved_job_lock = nil
  l_2_0.none.job_lock = nil
  l_2_0.none.money_lock = nil
  l_2_0.none.upgrade_lock = nil
  l_2_0.none.achievment_lock = nil
end

AssetsTweakData._init_risk_assets = function(l_3_0, l_3_1)
  l_3_0.risk_pd = {}
  l_3_0.risk_pd.name_id = "menu_asset_risklevel_0"
  l_3_0.risk_pd.texture = "guis/textures/pd2/mission_briefing/assets/assets_risklevel_0"
  l_3_0.risk_pd.stages = "all"
  l_3_0.risk_pd.risk_lock = 0
  l_3_0.risk_swat = {}
  l_3_0.risk_swat.name_id = "menu_asset_risklevel_1"
  l_3_0.risk_swat.texture = "guis/textures/pd2/mission_briefing/assets/assets_risklevel_1"
  l_3_0.risk_swat.stages = "all"
  l_3_0.risk_swat.risk_lock = 1
  l_3_0.risk_fbi = {}
  l_3_0.risk_fbi.name_id = "menu_asset_risklevel_2"
  l_3_0.risk_fbi.texture = "guis/textures/pd2/mission_briefing/assets/assets_risklevel_2"
  l_3_0.risk_fbi.stages = "all"
  l_3_0.risk_fbi.risk_lock = 2
  l_3_0.risk_death_squad = {}
  l_3_0.risk_death_squad.name_id = "menu_asset_risklevel_3"
  l_3_0.risk_death_squad.texture = "guis/textures/pd2/mission_briefing/assets/assets_risklevel_3"
  l_3_0.risk_death_squad.stages = "all"
  l_3_0.risk_death_squad.risk_lock = 3
end

AssetsTweakData._init_assets = function(l_4_0, l_4_1)
  l_4_0.ukrainian_job_tiara = {}
  l_4_0.ukrainian_job_tiara.name_id = "menu_asset_test_jewelry_store_tiara"
  l_4_0.ukrainian_job_tiara.texture = "guis/textures/pd2/mission_briefing/assets/ukranian_job/asset01"
  l_4_0.ukrainian_job_tiara.stages = {"ukrainian_job"}
  l_4_0.ukrainian_job_tiara.no_mystery = true
  l_4_0.ukrainian_job_front = {}
  l_4_0.ukrainian_job_front.name_id = "menu_asset_test_jewelry_store_front"
  l_4_0.ukrainian_job_front.texture = "guis/textures/pd2/mission_briefing/assets/ukranian_job/asset02"
  l_4_0.ukrainian_job_front.stages = {"ukrainian_job"}
  l_4_0.ukrainian_job_cam = {}
  l_4_0.ukrainian_job_cam.name_id = "menu_asset_cam"
  l_4_0.ukrainian_job_cam.texture = "guis/textures/pd2/mission_briefing/assets/ukranian_job/asset07"
  l_4_0.ukrainian_job_cam.stages = {"ukrainian_job"}
  l_4_0.ukrainian_job_cam.visible_if_locked = true
  l_4_0.ukrainian_job_cam.unlock_desc_id = "menu_asset_cam_desc"
  l_4_0.ukrainian_job_cam.no_mystery = true
  l_4_0.ukrainian_job_cam.money_lock = l_4_1:get_value("money_manager", "mission_asset_cost_small", 6)
  l_4_0.ukrainian_job_metal_detector = {}
  l_4_0.ukrainian_job_metal_detector.name_id = "menu_asset_test_jewelry_store_blueprint"
  l_4_0.ukrainian_job_metal_detector.texture = "guis/textures/pd2/mission_briefing/assets/ukranian_job/asset05"
  l_4_0.ukrainian_job_metal_detector.stages = {"ukrainian_job"}
  l_4_0.ukrainian_job_shutter = {}
  l_4_0.ukrainian_job_shutter.name_id = "menu_asset_test_jewelry_store_code"
  l_4_0.ukrainian_job_shutter.unlock_desc_id = "menu_asset_ukrainian_job_shutter_desc"
  l_4_0.ukrainian_job_shutter.texture = "guis/textures/pd2/mission_briefing/assets/ukranian_job/asset06"
  l_4_0.ukrainian_job_shutter.stages = {"ukrainian_job"}
  l_4_0.ukrainian_job_shutter.no_mystery = true
  l_4_0.ukrainian_job_shutter.money_lock = l_4_1:get_value("money_manager", "mission_asset_cost_small", 3)
  l_4_0.security_safe_05x05 = {}
  l_4_0.security_safe_05x05.name_id = "menu_asset_test_jewelry_store_safe"
  l_4_0.security_safe_05x05.texture = "guis/textures/pd2/mission_briefing/assets/ukranian_job/asset04"
  l_4_0.security_safe_05x05.stages = {"ukrainian_job"}
  l_4_0.welcome_to_the_jungle_keycard = {}
  l_4_0.welcome_to_the_jungle_keycard.name_id = "menu_asset_welcome_to_the_jungle_keycard"
  l_4_0.welcome_to_the_jungle_keycard.unlock_desc_id = "menu_asset_welcome_to_the_jungle_keycard_desc"
  l_4_0.welcome_to_the_jungle_keycard.texture = "guis/textures/pd2/mission_briefing/assets/big_oil/day2/asset07"
  l_4_0.welcome_to_the_jungle_keycard.stages = {"welcome_to_the_jungle_2"}
  l_4_0.welcome_to_the_jungle_keycard.job_lock = "keycard"
  l_4_0.welcome_to_the_jungle_shuttercode = {}
  l_4_0.welcome_to_the_jungle_shuttercode.name_id = "menu_asset_welcome_to_the_jungle_shuttercode"
  l_4_0.welcome_to_the_jungle_shuttercode.unlock_desc_id = "menu_asset_welcome_to_the_jungle_shuttercode_desc"
  l_4_0.welcome_to_the_jungle_shuttercode.texture = "guis/textures/pd2/mission_briefing/assets/big_oil/day2/asset02"
  l_4_0.welcome_to_the_jungle_shuttercode.stages = {"welcome_to_the_jungle_2"}
  l_4_0.welcome_to_the_jungle_shuttercode.job_lock = "shuttercode"
  l_4_0.welcome_to_the_jungle_plane_keys = {}
  l_4_0.welcome_to_the_jungle_plane_keys.name_id = "menu_asset_welcome_to_the_jungle_plane_keys"
  l_4_0.welcome_to_the_jungle_plane_keys.unlock_desc_id = "menu_asset_welcome_to_the_jungle_plane_keys_desc"
  l_4_0.welcome_to_the_jungle_plane_keys.texture = "guis/textures/pd2/mission_briefing/assets/big_oil/day2/asset05"
  l_4_0.welcome_to_the_jungle_plane_keys.stages = {"welcome_to_the_jungle_2"}
  l_4_0.welcome_to_the_jungle_plane_keys.job_lock = "planekeys"
  l_4_0.welcome_to_the_jungle_blueprints = {}
  l_4_0.welcome_to_the_jungle_blueprints.name_id = "menu_asset_welcome_to_the_jungle_blueprints"
  l_4_0.welcome_to_the_jungle_blueprints.unlock_desc_id = "menu_asset_welcome_to_the_jungle_blueprints_desc"
  l_4_0.welcome_to_the_jungle_blueprints.texture = "guis/textures/pd2/mission_briefing/assets/big_oil/day2/asset09"
  l_4_0.welcome_to_the_jungle_blueprints.stages = {"welcome_to_the_jungle_2"}
  l_4_0.welcome_to_the_jungle_blueprints.job_lock = "blueprints"
  l_4_0.welcome_to_the_jungle_fusion = {}
  l_4_0.welcome_to_the_jungle_fusion.name_id = "menu_asset_welcome_to_the_jungle_fusion"
  l_4_0.welcome_to_the_jungle_fusion.unlock_desc_id = "menu_asset_welcome_to_the_jungle_fusion_desc"
  l_4_0.welcome_to_the_jungle_fusion.texture = "guis/textures/pd2/mission_briefing/assets/big_oil/day2/asset08"
  l_4_0.welcome_to_the_jungle_fusion.stages = {"welcome_to_the_jungle_2"}
  l_4_0.welcome_to_the_jungle_fusion.job_lock = "fusion"
  l_4_0.welcome_to_the_jungle_guards = {}
  l_4_0.welcome_to_the_jungle_guards.name_id = "menu_asset_welcome_to_the_jungle_guards"
  l_4_0.welcome_to_the_jungle_guards.unlock_desc_id = "menu_asset_welcome_to_the_jungle_guards_desc"
  l_4_0.welcome_to_the_jungle_guards.texture = "guis/textures/pd2/mission_briefing/assets/big_oil/day2/asset06"
  l_4_0.welcome_to_the_jungle_guards.stages = {"welcome_to_the_jungle_2"}
  l_4_0.welcome_to_the_jungle_guards.job_lock = "guards"
  l_4_0.welcome_to_the_jungle_rossy = {}
  l_4_0.welcome_to_the_jungle_rossy.name_id = "menu_asset_welcome_to_the_jungle_rossy"
  l_4_0.welcome_to_the_jungle_rossy.unlock_desc_id = "menu_asset_welcome_to_the_jungle_rossy_desc"
  l_4_0.welcome_to_the_jungle_rossy.texture = "guis/textures/pd2/mission_briefing/assets/big_oil/day2/asset04"
  l_4_0.welcome_to_the_jungle_rossy.stages = {"welcome_to_the_jungle_2"}
  l_4_0.welcome_to_the_jungle_rossy.job_lock = "rossy"
  l_4_0.election_day_2_gold = {}
  l_4_0.election_day_2_gold.name_id = "menu_asset_election_day_2_gold"
  l_4_0.election_day_2_gold.texture = "guis/textures/pd2/mission_briefing/assets/ukranian_job/asset05"
  l_4_0.election_day_2_gold.stages = {"election_day_2"}
  l_4_0.election_day_2_gold.visible_if_locked = true
  l_4_0.election_day_2_gold.unlock_desc_id = "menu_asset_election_day_2_gold_desc"
  l_4_0.election_day_2_gold.money_lock = l_4_1:get_value("money_manager", "mission_asset_cost_small", 4)
  l_4_0.election_day_2_gold.no_mystery = true
  l_4_0.election_day_2_money = {}
  l_4_0.election_day_2_money.name_id = "menu_asset_election_day_2_money"
  l_4_0.election_day_2_money.texture = "guis/textures/pd2/mission_briefing/assets/ukranian_job/asset06"
  l_4_0.election_day_2_money.stages = {"election_day_2"}
  l_4_0.election_day_2_money.visible_if_locked = true
  l_4_0.election_day_2_money.unlock_desc_id = "menu_asset_election_day_2_money_desc"
  l_4_0.election_day_2_money.no_mystery = true
  l_4_0.election_day_2_money.money_lock = l_4_1:get_value("money_manager", "mission_asset_cost_small", 3)
  l_4_0.election_day_2_painting = {}
  l_4_0.election_day_2_painting.name_id = "menu_asset_election_day_2_painting"
  l_4_0.election_day_2_painting.texture = "guis/textures/pd2/mission_briefing/assets/ukranian_job/asset06"
  l_4_0.election_day_2_painting.stages = {"election_day_2"}
  l_4_0.election_day_2_painting.visible_if_locked = true
  l_4_0.election_day_2_painting.unlock_desc_id = "menu_asset_election_day_2_painting_desc"
  l_4_0.election_day_2_painting.no_mystery = true
  l_4_0.election_day_2_painting.money_lock = l_4_1:get_value("money_manager", "mission_asset_cost_small", 2)
  l_4_0.watchdogs_1_ammo = {}
  l_4_0.watchdogs_1_ammo.name_id = "menu_asset_ammo"
  l_4_0.watchdogs_1_ammo.texture = "guis/textures/pd2/mission_briefing/assets/watch_dogs/day1/asset01"
  l_4_0.watchdogs_1_ammo.stages = {"watchdogs_1"}
  l_4_0.watchdogs_1_ammo.visible_if_locked = true
  l_4_0.watchdogs_1_ammo.unlock_desc_id = "menu_asset_ammo_desc"
  l_4_0.watchdogs_1_ammo.no_mystery = true
  l_4_0.watchdogs_1_ammo.money_lock = l_4_1:get_value("money_manager", "mission_asset_cost_small", 3)
  l_4_0.watchdogs_1_health = {}
  l_4_0.watchdogs_1_health.name_id = "menu_asset_health"
  l_4_0.watchdogs_1_health.texture = "guis/textures/pd2/mission_briefing/assets/watch_dogs/day1/asset02"
  l_4_0.watchdogs_1_health.stages = {"watchdogs_1"}
  l_4_0.watchdogs_1_health.visible_if_locked = true
  l_4_0.watchdogs_1_health.unlock_desc_id = "menu_asset_health_desc"
  l_4_0.watchdogs_1_health.no_mystery = true
  l_4_0.watchdogs_1_health.money_lock = l_4_1:get_value("money_manager", "mission_asset_cost_small", 3)
  l_4_0.watchdogs_1_escape_car = {}
  l_4_0.watchdogs_1_escape_car.name_id = "menu_asset_watchdogs_escape"
  l_4_0.watchdogs_1_escape_car.texture = "guis/textures/pd2/mission_briefing/assets/watch_dogs/day1/escapecar"
  l_4_0.watchdogs_1_escape_car.stages = {"watchdogs_1"}
  l_4_0.watchdogs_1_escape_car.visible_if_locked = true
  l_4_0.watchdogs_1_escape_car.unlock_desc_id = "menu_asset_watchdogs_escape_desc"
  l_4_0.watchdogs_1_escape_car.no_mystery = true
  l_4_0.watchdogs_1_escape_car.money_lock = l_4_1:get_value("money_manager", "mission_asset_cost_small", 7)
  l_4_0.watchdogs_2_ammo = {}
  l_4_0.watchdogs_2_ammo.name_id = "menu_asset_ammo"
  l_4_0.watchdogs_2_ammo.texture = "guis/textures/pd2/mission_briefing/assets/watch_dogs/day2/assets_watchdogs2_ammo"
  l_4_0.watchdogs_2_ammo.stages = {"watchdogs_2"}
  l_4_0.watchdogs_2_ammo.visible_if_locked = true
  l_4_0.watchdogs_2_ammo.unlock_desc_id = "menu_asset_ammo_desc"
  l_4_0.watchdogs_2_ammo.no_mystery = true
  l_4_0.watchdogs_2_ammo.money_lock = l_4_1:get_value("money_manager", "mission_asset_cost_small", 3)
  l_4_0.watchdogs_2_health = {}
  l_4_0.watchdogs_2_health.name_id = "menu_asset_health"
  l_4_0.watchdogs_2_health.texture = "guis/textures/pd2/mission_briefing/assets/watch_dogs/day2/assets_watchdogs2_medic"
  l_4_0.watchdogs_2_health.stages = {"watchdogs_2"}
  l_4_0.watchdogs_2_health.visible_if_locked = true
  l_4_0.watchdogs_2_health.unlock_desc_id = "menu_asset_health_desc"
  l_4_0.watchdogs_2_health.no_mystery = true
  l_4_0.watchdogs_2_health.money_lock = l_4_1:get_value("money_manager", "mission_asset_cost_small", 3)
  l_4_0.watchdogs_2_sniper = {}
  l_4_0.watchdogs_2_sniper.name_id = "menu_asset_sniper"
  l_4_0.watchdogs_2_sniper.texture = "guis/textures/pd2/mission_briefing/assets/watch_dogs/day2/assets_watchdogs_sniper"
  l_4_0.watchdogs_2_sniper.stages = {"watchdogs_2"}
  l_4_0.watchdogs_2_sniper.visible_if_locked = true
  l_4_0.watchdogs_2_sniper.unlock_desc_id = "menu_asset_sniper_desc"
  l_4_0.watchdogs_2_sniper.no_mystery = true
  l_4_0.watchdogs_2_sniper.money_lock = l_4_1:get_value("money_manager", "mission_asset_cost_small", 6)
  l_4_0.firestarter_1_ammo = {}
  l_4_0.firestarter_1_ammo.name_id = "menu_asset_ammo"
  l_4_0.firestarter_1_ammo.texture = "guis/textures/pd2/mission_briefing/assets/watch_dogs/day1/asset01"
  l_4_0.firestarter_1_ammo.stages = {"firestarter_1"}
  l_4_0.firestarter_1_ammo.visible_if_locked = true
  l_4_0.firestarter_1_ammo.unlock_desc_id = "menu_asset_ammo_desc"
  l_4_0.firestarter_1_ammo.no_mystery = true
  l_4_0.firestarter_1_ammo.money_lock = l_4_1:get_value("money_manager", "mission_asset_cost_small", 3)
  l_4_0.firestarter_1_health = {}
  l_4_0.firestarter_1_health.name_id = "menu_asset_health"
  l_4_0.firestarter_1_health.texture = "guis/textures/pd2/mission_briefing/assets/watch_dogs/day1/asset02"
  l_4_0.firestarter_1_health.stages = {"firestarter_1"}
  l_4_0.firestarter_1_health.visible_if_locked = true
  l_4_0.firestarter_1_health.unlock_desc_id = "menu_asset_health_desc"
  l_4_0.firestarter_1_health.no_mystery = true
  l_4_0.firestarter_1_health.money_lock = l_4_1:get_value("money_manager", "mission_asset_cost_small", 3)
  l_4_0.firestarter_2_cam = {}
  l_4_0.firestarter_2_cam.name_id = "menu_asset_cam"
  l_4_0.firestarter_2_cam.texture = "guis/textures/pd2/mission_briefing/assets/big_oil/day2/asset03"
  l_4_0.firestarter_2_cam.stages = {"firestarter_2"}
  l_4_0.firestarter_2_cam.visible_if_locked = true
  l_4_0.firestarter_2_cam.unlock_desc_id = "menu_asset_cam_desc"
  l_4_0.firestarter_2_cam.no_mystery = true
  l_4_0.firestarter_2_cam.money_lock = l_4_1:get_value("money_manager", "mission_asset_cost_small", 7)
  l_4_0.firestarter_3_insiderinfo = {}
  l_4_0.firestarter_3_insiderinfo.name_id = "menu_asset_branchbank_insiderinfo"
  l_4_0.firestarter_3_insiderinfo.texture = "guis/textures/pd2/mission_briefing/assets/bank/assets_bank_insiderinfo"
  l_4_0.firestarter_3_insiderinfo.stages = {"firestarter_3"}
  l_4_0.firestarter_3_insiderinfo.visible_if_locked = true
  l_4_0.firestarter_3_insiderinfo.unlock_desc_id = "menu_asset_branchbank_insiderinfo_desc"
  l_4_0.firestarter_3_insiderinfo.no_mystery = true
  l_4_0.firestarter_3_insiderinfo.money_lock = l_4_1:get_value("money_manager", "mission_asset_cost_small", 2)
  l_4_0.firestarter_3_map_basic = {}
  l_4_0.firestarter_3_map_basic.name_id = "menu_asset_branchbank_blueprint"
  l_4_0.firestarter_3_map_basic.texture = "guis/textures/pd2/mission_briefing/assets/bank/assets_bank_blueprint"
  l_4_0.firestarter_3_map_basic.stages = {"firestarter_3"}
  l_4_0.firestarter_3_map_basic.visible_if_locked = true
  l_4_0.firestarter_3_map_basic.unlock_desc_id = "menu_asset_branchbank_blueprint_unlock_desc"
  l_4_0.firestarter_3_map_basic.no_mystery = true
  l_4_0.framing_frame_1_blueprint = {}
  l_4_0.framing_frame_1_blueprint.name_id = "menu_asset_framing_frame_1_blueprint"
  l_4_0.framing_frame_1_blueprint.texture = "guis/textures/pd2/mission_briefing/assets/framing_frame/day1/assets_framingframe_blueprint"
  l_4_0.framing_frame_1_blueprint.stages = {"framing_frame_1"}
  l_4_0.framing_frame_1_ammo = {}
  l_4_0.framing_frame_1_ammo.name_id = "menu_asset_ammo"
  l_4_0.framing_frame_1_ammo.texture = "guis/textures/pd2/mission_briefing/assets/framing_frame/day1/assets_framingframe_ammo"
  l_4_0.framing_frame_1_ammo.stages = {"framing_frame_1"}
  l_4_0.framing_frame_1_ammo.visible_if_locked = true
  l_4_0.framing_frame_1_ammo.unlock_desc_id = "menu_asset_framing_frame_1_ammo_desc"
  l_4_0.framing_frame_1_ammo.no_mystery = true
  l_4_0.framing_frame_1_ammo.money_lock = l_4_1:get_value("money_manager", "mission_asset_cost_small", 4)
  l_4_0.framing_frame_1_health = {}
  l_4_0.framing_frame_1_health.name_id = "menu_asset_health"
  l_4_0.framing_frame_1_health.texture = "guis/textures/pd2/mission_briefing/assets/framing_frame/day1/assets_framingframe_medic"
  l_4_0.framing_frame_1_health.stages = {"framing_frame_1"}
  l_4_0.framing_frame_1_health.visible_if_locked = true
  l_4_0.framing_frame_1_health.unlock_desc_id = "menu_asset_framing_frame_1_health_desc"
  l_4_0.framing_frame_1_health.no_mystery = true
  l_4_0.framing_frame_1_health.money_lock = l_4_1:get_value("money_manager", "mission_asset_cost_small", 4)
  l_4_0.framing_frame_1_cam = {}
  l_4_0.framing_frame_1_cam.name_id = "menu_asset_cam"
  l_4_0.framing_frame_1_cam.texture = "guis/textures/pd2/mission_briefing/assets/framing_frame/day1/assets_framingframe_cam"
  l_4_0.framing_frame_1_cam.stages = {"framing_frame_1"}
  l_4_0.framing_frame_1_cam.visible_if_locked = true
  l_4_0.framing_frame_1_cam.unlock_desc_id = "menu_asset_cam_desc"
  l_4_0.framing_frame_1_cam.no_mystery = true
  l_4_0.framing_frame_1_cam.money_lock = l_4_1:get_value("money_manager", "mission_asset_cost_small", 6)
  l_4_0.framing_frame_1_keycard = {}
  l_4_0.framing_frame_1_keycard.name_id = "menu_asset_framing_frame_1_keycard"
  l_4_0.framing_frame_1_keycard.texture = "guis/textures/pd2/mission_briefing/assets/framing_frame/day1/assets_framingframe_keycard"
  l_4_0.framing_frame_1_keycard.stages = {"framing_frame_1"}
  l_4_0.framing_frame_1_keycard.visible_if_locked = true
  l_4_0.framing_frame_1_keycard.unlock_desc_id = "menu_asset_framing_frame_1_keycard_desc"
  l_4_0.framing_frame_1_keycard.no_mystery = true
  l_4_0.framing_frame_1_keycard.money_lock = l_4_1:get_value("money_manager", "mission_asset_cost_small", 10)
  l_4_0.framing_frame_1_keycard.upgrade_lock = {category = "player", upgrade = "additional_assets"}
  l_4_0.framing_frame_1_art = {}
  l_4_0.framing_frame_1_art.name_id = "menu_asset_framing_frame_art"
  l_4_0.framing_frame_1_art.texture = "guis/textures/pd2/mission_briefing/assets/framing_frame/day1/assets_framingframe_art"
  l_4_0.framing_frame_1_art.stages = {"framing_frame_1"}
  l_4_0.framing_frame_1_art.visible_if_locked = true
  l_4_0.framing_frame_1_art.unlock_desc_id = "menu_asset_framing_frame_art_desc"
  l_4_0.framing_frame_1_art.no_mystery = true
  l_4_0.framing_frame_1_art.money_lock = l_4_1:get_value("money_manager", "mission_asset_cost_small", 3)
  l_4_0.framing_frame_1_truck = {}
  l_4_0.framing_frame_1_truck.name_id = "menu_asset_framing_frame_truck"
  l_4_0.framing_frame_1_truck.texture = "guis/textures/pd2/mission_briefing/assets/framing_frame/day1/assets_framingframe_roofaccess"
  l_4_0.framing_frame_1_truck.stages = {"framing_frame_1"}
  l_4_0.framing_frame_1_truck.visible_if_locked = true
  l_4_0.framing_frame_1_truck.unlock_desc_id = "menu_asset_framing_frame_truck_desc"
  l_4_0.framing_frame_1_truck.no_mystery = true
  l_4_0.framing_frame_1_truck.money_lock = l_4_1:get_value("money_manager", "mission_asset_cost_small", 2)
  l_4_0.framing_frame_2_sniper = {}
  l_4_0.framing_frame_2_sniper.name_id = "menu_asset_sniper"
  l_4_0.framing_frame_2_sniper.texture = "guis/textures/pd2/mission_briefing/assets/framing_frame/day2/asset01"
  l_4_0.framing_frame_2_sniper.stages = {"framing_frame_2"}
  l_4_0.framing_frame_2_sniper.visible_if_locked = true
  l_4_0.framing_frame_2_sniper.unlock_desc_id = "menu_asset_sniper_desc"
  l_4_0.framing_frame_2_sniper.no_mystery = true
  l_4_0.framing_frame_2_sniper.money_lock = l_4_1:get_value("money_manager", "mission_asset_cost_small", 6)
  l_4_0.framing_frame_3_ammo = {}
  l_4_0.framing_frame_3_ammo.name_id = "menu_asset_ammo"
  l_4_0.framing_frame_3_ammo.texture = "guis/textures/pd2/mission_briefing/assets/watch_dogs/day1/asset01"
  l_4_0.framing_frame_3_ammo.stages = {"framing_frame_3"}
  l_4_0.framing_frame_3_ammo.visible_if_locked = true
  l_4_0.framing_frame_3_ammo.unlock_desc_id = "menu_asset_ammo_desc"
  l_4_0.framing_frame_3_ammo.no_mystery = true
  l_4_0.framing_frame_3_ammo.money_lock = l_4_1:get_value("money_manager", "mission_asset_cost_small", 3)
  l_4_0.framing_frame_3_health = {}
  l_4_0.framing_frame_3_health.name_id = "menu_asset_health"
  l_4_0.framing_frame_3_health.texture = "guis/textures/pd2/mission_briefing/assets/watch_dogs/day1/asset02"
  l_4_0.framing_frame_3_health.stages = {"framing_frame_3"}
  l_4_0.framing_frame_3_health.visible_if_locked = true
  l_4_0.framing_frame_3_health.unlock_desc_id = "menu_asset_health_desc"
  l_4_0.framing_frame_3_health.no_mystery = true
  l_4_0.framing_frame_3_health.money_lock = l_4_1:get_value("money_manager", "mission_asset_cost_small", 3)
  l_4_0.framing_frame_3_vent = {}
  l_4_0.framing_frame_3_vent.name_id = "menu_asset_framing3_vent"
  l_4_0.framing_frame_3_vent.texture = "guis/textures/pd2/mission_briefing/assets/framing_frame/day3/asset01"
  l_4_0.framing_frame_3_vent.stages = {"framing_frame_3"}
  l_4_0.framing_frame_3_vent.visible_if_locked = true
  l_4_0.framing_frame_3_vent.unlock_desc_id = "menu_asset_framing3_vent_desc"
  l_4_0.framing_frame_3_vent.no_mystery = true
  l_4_0.framing_frame_3_vent.money_lock = l_4_1:get_value("money_manager", "mission_asset_cost_small", 2)
  l_4_0.election_day_2_ammo = {}
  l_4_0.election_day_2_ammo.name_id = "menu_asset_ammo"
  l_4_0.election_day_2_ammo.texture = "guis/textures/pd2/mission_briefing/assets/ukranian_job/asset06"
  l_4_0.election_day_2_ammo.stages = {"election_day_2"}
  l_4_0.election_day_2_ammo.visible_if_locked = true
  l_4_0.election_day_2_ammo.unlock_desc_id = "menu_asset_ammo_desc"
  l_4_0.election_day_2_ammo.no_mystery = true
  l_4_0.election_day_2_ammo.money_lock = l_4_1:get_value("money_manager", "mission_asset_cost_small", 2)
  l_4_0.election_day_2_health = {}
  l_4_0.election_day_2_health.name_id = "menu_asset_h"
  l_4_0.election_day_2_health.texture = "guis/textures/pd2/mission_briefing/assets/ukranian_job/asset06"
  l_4_0.election_day_2_health.stages = {"election_day_2"}
  l_4_0.election_day_2_health.visible_if_locked = true
  l_4_0.election_day_2_health.unlock_desc_id = "menu_asset_health_desc"
  l_4_0.election_day_2_health.no_mystery = true
  l_4_0.election_day_2_health.money_lock = l_4_1:get_value("money_manager", "mission_asset_cost_small", 2)
  l_4_0.election_day_3_ammo = {}
  l_4_0.election_day_3_ammo.name_id = "menu_asset_ammo"
  l_4_0.election_day_3_ammo.texture = "guis/textures/pd2/mission_briefing/assets/ukranian_job/asset06"
  l_4_0.election_day_3_ammo.stages = {"election_day_3"}
  l_4_0.election_day_3_ammo.visible_if_locked = true
  l_4_0.election_day_3_ammo.unlock_desc_id = "menu_asset_ammo_desc"
  l_4_0.election_day_3_ammo.no_mystery = true
  l_4_0.election_day_3_ammo.money_lock = l_4_1:get_value("money_manager", "mission_asset_cost_small", 2)
  l_4_0.election_day_3_health = {}
  l_4_0.election_day_3_health.name_id = "menu_asset_health"
  l_4_0.election_day_3_health.texture = "guis/textures/pd2/mission_briefing/assets/ukranian_job/asset06"
  l_4_0.election_day_3_health.stages = {"election_day_3"}
  l_4_0.election_day_3_health.visible_if_locked = true
  l_4_0.election_day_3_health.unlock_desc_id = "menu_asset_health_desc"
  l_4_0.election_day_3_health.no_mystery = true
  l_4_0.election_day_3_health.money_lock = l_4_1:get_value("money_manager", "mission_asset_cost_small", 2)
  l_4_0.jungle_1_bikers = {}
  l_4_0.jungle_1_bikers.name_id = "menu_asset_big_oil_1_bikers"
  l_4_0.jungle_1_bikers.texture = "guis/textures/pd2/mission_briefing/assets/big_oil/day1/big_oil_1_biker_gang"
  l_4_0.jungle_1_bikers.stages = {"welcome_to_the_jungle_1"}
  l_4_0.jungle_1_bikers.visible_if_locked = true
  l_4_0.jungle_1_bikers.unlock_desc_id = "menu_asset_big_oil_1_bikers_desc"
  l_4_0.jungle_1_bikers.no_mystery = true
  l_4_0.jungle_2_gas = {}
  l_4_0.jungle_2_gas.name_id = "menu_asset_jungle_2_gas"
  l_4_0.jungle_2_gas.texture = "guis/textures/pd2/mission_briefing/assets/big_oil/day2/asset01"
  l_4_0.jungle_2_gas.stages = {"welcome_to_the_jungle_2"}
  l_4_0.jungle_2_gas.visible_if_locked = true
  l_4_0.jungle_2_gas.unlock_desc_id = "menu_asset_jungle_2_gas_desc"
  l_4_0.jungle_2_gas.no_mystery = true
  l_4_0.jungle_2_gas.money_lock = l_4_1:get_value("money_manager", "mission_asset_cost_small", 2)
  l_4_0.jungle_2_cam = {}
  l_4_0.jungle_2_cam.name_id = "menu_asset_cam"
  l_4_0.jungle_2_cam.texture = "guis/textures/pd2/mission_briefing/assets/big_oil/day2/asset03"
  l_4_0.jungle_2_cam.stages = {"welcome_to_the_jungle_2"}
  l_4_0.jungle_2_cam.visible_if_locked = true
  l_4_0.jungle_2_cam.unlock_desc_id = "menu_asset_cam_desc"
  l_4_0.jungle_2_cam.no_mystery = true
  l_4_0.jungle_2_cam.money_lock = l_4_1:get_value("money_manager", "mission_asset_cost_small", 2)
  l_4_0.jungle_2_ammo = {}
  l_4_0.jungle_2_ammo.name_id = "menu_asset_jungle_2_ammo"
  l_4_0.jungle_2_ammo.texture = "guis/textures/pd2/mission_briefing/assets/watch_dogs/day1/asset01"
  l_4_0.jungle_2_ammo.stages = {"welcome_to_the_jungle_2"}
  l_4_0.jungle_2_ammo.visible_if_locked = true
  l_4_0.jungle_2_ammo.unlock_desc_id = "menu_asset_jungle_2_ammo_desc"
  l_4_0.jungle_2_ammo.no_mystery = true
  l_4_0.jungle_2_ammo.money_lock = l_4_1:get_value("money_manager", "mission_asset_cost_small", 2)
  l_4_0.branchbank_ammo = {}
  l_4_0.branchbank_ammo.name_id = "menu_asset_branchbank_ammo"
  l_4_0.branchbank_ammo.texture = "guis/textures/pd2/mission_briefing/assets/bank/assets_bank_ammo"
  l_4_0.branchbank_ammo.stages = {"branchbank"}
  l_4_0.branchbank_ammo.visible_if_locked = true
  l_4_0.branchbank_ammo.unlock_desc_id = "menu_asset_branchbank_ammo_desc"
  l_4_0.branchbank_ammo.no_mystery = true
  l_4_0.branchbank_ammo.money_lock = l_4_1:get_value("money_manager", "mission_asset_cost_small", 3)
  l_4_0.branchbank_health = {}
  l_4_0.branchbank_health.name_id = "menu_asset_health"
  l_4_0.branchbank_health.texture = "guis/textures/pd2/mission_briefing/assets/bank/assets_bank_medicbag"
  l_4_0.branchbank_health.stages = {"branchbank"}
  l_4_0.branchbank_health.visible_if_locked = true
  l_4_0.branchbank_health.unlock_desc_id = "menu_asset_health_desc"
  l_4_0.branchbank_health.no_mystery = true
  l_4_0.branchbank_health.money_lock = l_4_1:get_value("money_manager", "mission_asset_cost_small", 3)
  l_4_0.branchbank_cam = {}
  l_4_0.branchbank_cam.name_id = "menu_asset_cam"
  l_4_0.branchbank_cam.texture = "guis/textures/pd2/mission_briefing/assets/big_oil/day2/asset03"
  l_4_0.branchbank_cam.stages = {"branchbank"}
  l_4_0.branchbank_cam.visible_if_locked = true
  l_4_0.branchbank_cam.unlock_desc_id = "menu_asset_cam_desc"
  l_4_0.branchbank_cam.no_mystery = true
  l_4_0.branchbank_cam.money_lock = l_4_1:get_value("money_manager", "mission_asset_cost_small", 6)
  l_4_0.branchbank_insiderinfo = {}
  l_4_0.branchbank_insiderinfo.name_id = "menu_asset_branchbank_insiderinfo"
  l_4_0.branchbank_insiderinfo.texture = "guis/textures/pd2/mission_briefing/assets/bank/assets_bank_insiderinfo"
  l_4_0.branchbank_insiderinfo.stages = {"branchbank"}
  l_4_0.branchbank_insiderinfo.visible_if_locked = true
  l_4_0.branchbank_insiderinfo.unlock_desc_id = "menu_asset_branchbank_insiderinfo_desc"
  l_4_0.branchbank_insiderinfo.no_mystery = true
  l_4_0.branchbank_insiderinfo.money_lock = l_4_1:get_value("money_manager", "mission_asset_cost_small", 2)
  l_4_0.branchbank_map_basic = {}
  l_4_0.branchbank_map_basic.name_id = "menu_asset_branchbank_blueprint"
  l_4_0.branchbank_map_basic.texture = "guis/textures/pd2/mission_briefing/assets/bank/assets_bank_blueprint"
  l_4_0.branchbank_map_basic.stages = {"branchbank"}
  l_4_0.branchbank_map_basic.visible_if_locked = true
  l_4_0.branchbank_map_basic.unlock_desc_id = "menu_asset_branchbank_blueprint_unlock_desc"
  l_4_0.branchbank_map_basic.no_mystery = true
  l_4_0.rat_1_ammo = {}
  l_4_0.rat_1_ammo.name_id = "menu_asset_ammo"
  l_4_0.rat_1_ammo.texture = "guis/textures/pd2/mission_briefing/assets/watch_dogs/day1/asset01"
  l_4_0.rat_1_ammo.texture = "guis/textures/pd2/mission_briefing/assets/watch_dogs/day1/asset01"
  l_4_0.rat_1_ammo.stages = {"alex_1"}
  l_4_0.rat_1_ammo.visible_if_locked = true
  l_4_0.rat_1_ammo.unlock_desc_id = "menu_asset_ammo_desc"
  l_4_0.rat_1_ammo.no_mystery = true
  l_4_0.rat_1_ammo.money_lock = l_4_1:get_value("money_manager", "mission_asset_cost_small", 3)
  l_4_0.rat_1_health = {}
  l_4_0.rat_1_health.name_id = "menu_asset_health"
  l_4_0.rat_1_health.texture = "guis/textures/pd2/mission_briefing/assets/watch_dogs/day1/asset02"
  l_4_0.rat_1_health.stages = {"alex_1"}
  l_4_0.rat_1_health.visible_if_locked = true
  l_4_0.rat_1_health.unlock_desc_id = "menu_asset_health_desc"
  l_4_0.rat_1_health.no_mystery = true
  l_4_0.rat_1_health.money_lock = l_4_1:get_value("money_manager", "mission_asset_cost_small", 3)
  l_4_0.rat_1_lights = {}
  l_4_0.rat_1_lights.name_id = "menu_asset_lights"
  l_4_0.rat_1_lights.texture = "guis/textures/pd2/mission_briefing/assets/rat/day1/asset01"
  l_4_0.rat_1_lights.stages = {"alex_1"}
  l_4_0.rat_1_lights.visible_if_locked = true
  l_4_0.rat_1_lights.unlock_desc_id = "menu_asset_lights_desc"
  l_4_0.rat_1_lights.no_mystery = true
  l_4_0.rat_1_lights.money_lock = l_4_1:get_value("money_manager", "mission_asset_cost_small", 3)
  l_4_0.rat_3_pilot = {}
  l_4_0.rat_3_pilot.name_id = "menu_asset_pilot"
  l_4_0.rat_3_pilot.texture = "guis/textures/pd2/mission_briefing/assets/rat/day3/asset01"
  l_4_0.rat_3_pilot.stages = {"alex_3"}
  l_4_0.rat_3_pilot.visible_if_locked = true
  l_4_0.rat_3_pilot.unlock_desc_id = "menu_asset_pilot_desc"
  l_4_0.rat_3_pilot.no_mystery = true
  l_4_0.rat_3_pilot.money_lock = l_4_1:get_value("money_manager", "mission_asset_cost_small", 3)
  l_4_0.mallcrasher_ammo = {}
  l_4_0.mallcrasher_ammo.name_id = "menu_asset_ammo"
  l_4_0.mallcrasher_ammo.texture = "guis/textures/pd2/mission_briefing/assets/watch_dogs/day1/asset01"
  l_4_0.mallcrasher_ammo.stages = {"mallcrasher"}
  l_4_0.mallcrasher_ammo.visible_if_locked = true
  l_4_0.mallcrasher_ammo.unlock_desc_id = "menu_asset_ammo_desc"
  l_4_0.mallcrasher_ammo.no_mystery = true
  l_4_0.mallcrasher_ammo.money_lock = l_4_1:get_value("money_manager", "mission_asset_cost_small", 2)
  l_4_0.mallcrasher_health = {}
  l_4_0.mallcrasher_health.name_id = "menu_asset_health"
  l_4_0.mallcrasher_health.texture = "guis/textures/pd2/mission_briefing/assets/watch_dogs/day1/asset02"
  l_4_0.mallcrasher_health.stages = {"mallcrasher"}
  l_4_0.mallcrasher_health.visible_if_locked = true
  l_4_0.mallcrasher_health.unlock_desc_id = "menu_asset_health_desc"
  l_4_0.mallcrasher_health.no_mystery = true
  l_4_0.mallcrasher_health.money_lock = l_4_1:get_value("money_manager", "mission_asset_cost_small", 2)
  l_4_0.mallcrasher_gascan_south = {}
  l_4_0.mallcrasher_gascan_south.name_id = "menu_asset_mallcrasher_gascan_south"
  l_4_0.mallcrasher_gascan_south.texture = "guis/textures/pd2/mission_briefing/assets/mallcrasher/asset01"
  l_4_0.mallcrasher_gascan_south.stages = {"mallcrasher"}
  l_4_0.mallcrasher_gascan_south.visible_if_locked = true
  l_4_0.mallcrasher_gascan_south.unlock_desc_id = "menu_asset_mallcrasher_gascan_south_desc"
  l_4_0.mallcrasher_gascan_south.no_mystery = true
  l_4_0.mallcrasher_gascan_south.money_lock = l_4_1:get_value("money_manager", "mission_asset_cost_small", 2)
  l_4_0.mallcrasher_gascan_north = {}
  l_4_0.mallcrasher_gascan_north.name_id = "menu_asset_mallcrasher_gascan_north"
  l_4_0.mallcrasher_gascan_north.texture = "guis/textures/pd2/mission_briefing/assets/mallcrasher/asset02"
  l_4_0.mallcrasher_gascan_north.stages = {"mallcrasher"}
  l_4_0.mallcrasher_gascan_north.visible_if_locked = true
  l_4_0.mallcrasher_gascan_north.unlock_desc_id = "menu_asset_mallcrasher_gascan_north_desc"
  l_4_0.mallcrasher_gascan_north.no_mystery = true
  l_4_0.mallcrasher_gascan_north.money_lock = l_4_1:get_value("money_manager", "mission_asset_cost_small", 2)
  l_4_0.nightclub_ammo = {}
  l_4_0.nightclub_ammo.name_id = "menu_asset_ammo"
  l_4_0.nightclub_ammo.texture = "guis/textures/pd2/mission_briefing/assets/watch_dogs/day1/asset01"
  l_4_0.nightclub_ammo.stages = {"nightclub"}
  l_4_0.nightclub_ammo.visible_if_locked = true
  l_4_0.nightclub_ammo.unlock_desc_id = "menu_asset_ammo_desc"
  l_4_0.nightclub_ammo.no_mystery = true
  l_4_0.nightclub_ammo.money_lock = l_4_1:get_value("money_manager", "mission_asset_cost_small", 2)
  l_4_0.nightclub_health = {}
  l_4_0.nightclub_health.name_id = "menu_asset_health"
  l_4_0.nightclub_health.texture = "guis/textures/pd2/mission_briefing/assets/watch_dogs/day1/asset02"
  l_4_0.nightclub_health.stages = {"nightclub"}
  l_4_0.nightclub_health.visible_if_locked = true
  l_4_0.nightclub_health.unlock_desc_id = "menu_asset_health_desc"
  l_4_0.nightclub_health.no_mystery = true
  l_4_0.nightclub_health.money_lock = l_4_1:get_value("money_manager", "mission_asset_cost_small", 2)
  l_4_0.nightclub_fire1 = {}
  l_4_0.nightclub_fire1.name_id = "menu_asset_nightclub_fire1"
  l_4_0.nightclub_fire1.texture = "guis/textures/pd2/mission_briefing/assets/nightclub/asset04"
  l_4_0.nightclub_fire1.stages = {"nightclub"}
  l_4_0.nightclub_fire1.visible_if_locked = true
  l_4_0.nightclub_fire1.unlock_desc_id = "menu_asset_nightclub_fire1_desc"
  l_4_0.nightclub_fire1.no_mystery = true
  l_4_0.nightclub_fire1.money_lock = l_4_1:get_value("money_manager", "mission_asset_cost_small", 2)
  l_4_0.nightclub_fire2 = {}
  l_4_0.nightclub_fire2.name_id = "menu_asset_nightclub_fire2"
  l_4_0.nightclub_fire2.texture = "guis/textures/pd2/mission_briefing/assets/nightclub/asset03"
  l_4_0.nightclub_fire2.stages = {"nightclub"}
  l_4_0.nightclub_fire2.visible_if_locked = true
  l_4_0.nightclub_fire2.unlock_desc_id = "menu_asset_nightclub_fire2_desc"
  l_4_0.nightclub_fire2.no_mystery = true
  l_4_0.nightclub_fire2.money_lock = l_4_1:get_value("money_manager", "mission_asset_cost_small", 2)
  l_4_0.nightclub_badmusic = {}
  l_4_0.nightclub_badmusic.name_id = "menu_asset_nightclub_badmusic"
  l_4_0.nightclub_badmusic.texture = "guis/textures/pd2/mission_briefing/assets/nightclub/asset02"
  l_4_0.nightclub_badmusic.stages = {"nightclub"}
  l_4_0.nightclub_badmusic.visible_if_locked = true
  l_4_0.nightclub_badmusic.unlock_desc_id = "menu_asset_nightclub_badmusic_desc"
  l_4_0.nightclub_badmusic.no_mystery = true
  l_4_0.nightclub_badmusic.money_lock = l_4_1:get_value("money_manager", "mission_asset_cost_small", 3)
  l_4_0.nightclub_lootpickup = {}
  l_4_0.nightclub_lootpickup.name_id = "menu_asset_nightclub_lootpickup"
  l_4_0.nightclub_lootpickup.texture = "guis/textures/pd2/mission_briefing/assets/nightclub/asset01"
  l_4_0.nightclub_lootpickup.stages = {"nightclub"}
  l_4_0.nightclub_lootpickup.visible_if_locked = true
  l_4_0.nightclub_lootpickup.unlock_desc_id = "menu_asset_nightclub_lootpickup_desc"
  l_4_0.nightclub_lootpickup.no_mystery = true
  l_4_0.nightclub_lootpickup.money_lock = l_4_1:get_value("money_manager", "mission_asset_cost_small", 5)
  l_4_0.four_stores_overview = {}
  l_4_0.four_stores_overview.name_id = "menu_asset_four_stores_overview"
  l_4_0.four_stores_overview.texture = "guis/textures/pd2/mission_briefing/assets/four_stores/asset01"
  l_4_0.four_stores_overview.stages = {"four_stores"}
end

AssetsTweakData._init_debug_assets = function(l_5_0, l_5_1)
  l_5_0.debug_1 = {}
  l_5_0.debug_1.name_id = "debug_1"
  l_5_0.debug_1.texture = "guis/textures/pd2/blackmarket/icons/armors/level_1"
  l_5_0.debug_1.money_lock = 10
  l_5_0.debug_1.stages = {"safehouse"}
  l_5_0.debug_1.visible_if_locked = true
  l_5_0.debug_2 = {}
  l_5_0.debug_2.name_id = "debug_2"
  l_5_0.debug_2.texture = "guis/textures/pd2/blackmarket/icons/armors/level_2"
  l_5_0.debug_2.stages = {"safehouse"}
  l_5_0.debug_2.money_lock = 20000
  l_5_0.debug_3 = {}
  l_5_0.debug_3.name_id = "debug_3"
  l_5_0.debug_3.texture = "guis/textures/pd2/blackmarket/icons/armors/level_3"
  l_5_0.debug_3.stages = {"safehouse"}
  l_5_0.debug_3.money_lock = 30
  l_5_0.debug_3.visible_if_locked = false
  l_5_0.debug_4 = {}
  l_5_0.debug_4.name_id = "debug_4"
  l_5_0.debug_4.texture = "guis/textures/pd2/blackmarket/icons/armors/level_4"
  l_5_0.debug_4.stages = {"safehouse"}
  l_5_0.debug_4.money_lock = 4000000
  l_5_0.debug_4.visible_if_locked = true
  l_5_0.debug_5 = {}
  l_5_0.debug_5.name_id = "debug_5"
  l_5_0.debug_5.texture = "guis/textures/pd2/blackmarket/icons/armors/level_5"
  l_5_0.debug_5.stages = {"safehouse"}
  l_5_0.debug_5.money_lock = 50
  l_5_0.debug_6 = {}
  l_5_0.debug_6.name_id = "debug_6"
  l_5_0.debug_6.texture = "guis/textures/pd2/blackmarket/icons/armors/level_6"
  l_5_0.debug_6.stages = {"safehouse"}
  l_5_0.debug_6.money_lock = 60000000
  l_5_0.debug_6.visible_if_locked = true
  l_5_0.debug_7 = {}
  l_5_0.debug_7.name_id = "debug_7"
  l_5_0.debug_7.texture = "guis/textures/pd2/blackmarket/icons/armors/level_7"
  l_5_0.debug_7.stages = {"safehouse"}
  l_5_0.debug_7.money_lock = 700
  l_5_0.debug_7.visible_if_locked = true
end


