-- Decompiled using luadec 2.0.1 by sztupy (http://winmo.sztupy.hu)
-- Command line was: F:\SteamLibrary\SteamApps\common\PAYDAY 2\lua\lib\tweak_data\playertweakdata.luac 

if not PlayerTweakData then
  PlayerTweakData = class()
end
PlayerTweakData._set_easy = function(l_1_0)
  l_1_0.damage.automatic_respawn_time = 150
end

PlayerTweakData._set_normal = function(l_2_0)
  l_2_0.damage.automatic_respawn_time = 120
end

PlayerTweakData._set_hard = function(l_3_0)
  l_3_0.damage.automatic_respawn_time = 220
  l_3_0.damage.DOWNED_TIME_DEC = 7
  l_3_0.damage.DOWNED_TIME_MIN = 5
end

PlayerTweakData._set_overkill = function(l_4_0)
  l_4_0.damage.DOWNED_TIME_DEC = 10
  l_4_0.damage.DOWNED_TIME_MIN = 5
end

PlayerTweakData._set_overkill_145 = function(l_5_0)
  l_5_0.damage.DOWNED_TIME_DEC = 15
  l_5_0.damage.DOWNED_TIME_MIN = 1
  l_5_0.damage.REVIVE_HEALTH_STEPS = {0.20000000298023}
end

PlayerTweakData.init = function(l_6_0)
  local is_console = SystemInfo:platform() ~= Idstring("WIN32")
  l_6_0.arrest = {arrest_timeout = 240, aggression_timeout = 60}
  l_6_0.put_on_mask_time = 2
  l_6_0.damage = {}
  if is_console then
    l_6_0.damage.ARMOR_INIT = 5
  else
    l_6_0.damage.ARMOR_INIT = 2
  end
  l_6_0.damage.ARMOR_STEPS = 1
  l_6_0.damage.ARMOR_DAMAGE_REDUCTION = 0
  l_6_0.damage.ARMOR_DAMAGE_REDUCTION_STEPS = {1, 0.60000002384186, 0.69999998807907, 0.80000001192093, 0.89999997615814, 0.94999998807907, 0.95999997854233, 0.97000002861023, 0.98000001907349, 0.99000000953674}
  l_6_0.damage.HEALTH_INIT = 20
  l_6_0.damage.LIVES_INIT = 4
  if is_console then
    l_6_0.damage.REGENERATE_TIME = 2
  else
    l_6_0.damage.REGENERATE_TIME = 2.7000000476837
  end
  l_6_0.damage.REVIVE_HEALTH_STEPS = {0.5}
  l_6_0.damage.BLEED_OT_TIME = 40
  l_6_0.damage.TASED_TIME = 10
  l_6_0.damage.TASED_RECOVER_TIME = 1
  l_6_0.damage.BLEED_OUT_HEALTH_INIT = 10
  l_6_0.damage.DOWNED_TIME = 30
  l_6_0.damage.DOWNED_TIME_DEC = 5
  l_6_0.damage.DOWNED_TIME_MIN = 10
  l_6_0.damage.ARRESTED_TIME = 60
  l_6_0.damage.INCAPACITATED_TIME = 30
  l_6_0.damage.MIN_DAMAGE_INTERVAL = 0.34999999403954
  l_6_0.damage.respawn_time_penalty = 30
  l_6_0.damage.base_respawn_time_penalty = 5
  l_6_0.fall_health_damage = 4
  l_6_0.fall_damage_alert_size = 250
  l_6_0.long_dis_interaction = {intimidate_strength = 0.5, highlight_range = 3000, intimidate_range_enemies = 1000, intimidate_range_civilians = 1000}
  l_6_0.suppression = {max_value = 20, decay_start_delay = 1, receive_mul = 10, spread_mul = 1, autohit_chance_mul = 1, tolerance = 1}
  l_6_0.suspicion = {max_value = 8, range_mul = 1, buildup_mul = 1}
  l_6_0.alarm_pager = {ring_delay = {2, 5}, ring_reminder = {4, 4}, ring_duration = {12, 12}, bluff_success_chance = {1, 1, 0}, bluff_success_chance_w_skill = {1, 1, 1, 1, 0}}
  l_6_0.TRANSITION_DURATION = 0.23000000417233
  l_6_0.stances = {default = {standard = {head = {}, shoulders = {}, vel_overshot = {}}, crouched = {head = {}, shoulders = {}, vel_overshot = {}}, steelsight = {shoulders = {}, vel_overshot = {}}}}
  l_6_0.stances.default.standard.head.translation = Vector3(0, 0, 145)
  l_6_0.stances.default.standard.head.rotation = Rotation()
  l_6_0.stances.default.standard.shakers = {}
  l_6_0.stances.default.standard.shakers.breathing = {}
  l_6_0.stances.default.standard.shakers.breathing.amplitude = 0.30000001192093
  l_6_0.stances.default.crouched.shakers = {}
  l_6_0.stances.default.crouched.shakers.breathing = {}
  l_6_0.stances.default.crouched.shakers.breathing.amplitude = 0.25
  l_6_0.stances.default.steelsight.shakers = {}
  l_6_0.stances.default.steelsight.shakers.breathing = {}
  l_6_0.stances.default.steelsight.shakers.breathing.amplitude = 0.025000000372529
  l_6_0.stances.default.mask_off = deep_clone(l_6_0.stances.default.standard)
  l_6_0.stances.default.mask_off.head.translation = Vector3(0, 0, 160)
  l_6_0.stances.default.clean = deep_clone(l_6_0.stances.default.mask_off)
  local pivot_head_translation = Vector3(7, 16, -0.5)
  local pivot_head_rotation = Rotation(0, 1, 0)
  local pivot_shoulder_translation = Vector3(8.4048595428467, 33.287200927734, -0.76365000009537)
  local pivot_shoulder_rotation = Rotation(0.1516939997673, 0.64449697732925, -1.1892000436783)
  l_6_0.stances.default.standard.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_6_0.stances.default.standard.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_6_0.stances.default.standard.vel_overshot.yaw_neg = 12
  l_6_0.stances.default.standard.vel_overshot.yaw_pos = -12
  l_6_0.stances.default.standard.vel_overshot.pitch_neg = -10
  l_6_0.stances.default.standard.vel_overshot.pitch_pos = 10
  l_6_0.stances.default.standard.vel_overshot.pivot = Vector3(20, 50, 0)
  l_6_0.stances.default.standard.FOV = 65
  l_6_0.stances.default.crouched.head.translation = Vector3(0, 0, 75)
  l_6_0.stances.default.crouched.head.rotation = Rotation()
  local pivot_head_translation = Vector3(6, 16, -0.5)
  local pivot_head_rotation = Rotation(-1, 1, 0)
  l_6_0.stances.default.crouched.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_6_0.stances.default.crouched.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_6_0.stances.default.crouched.vel_overshot.yaw_neg = 12
  l_6_0.stances.default.crouched.vel_overshot.yaw_pos = -12
  l_6_0.stances.default.crouched.vel_overshot.pitch_neg = -10
  l_6_0.stances.default.crouched.vel_overshot.pitch_pos = 10
  l_6_0.stances.default.crouched.vel_overshot.pivot = Vector3(20, 50, 0)
  l_6_0.stances.default.crouched.FOV = l_6_0.stances.default.standard.FOV
  local pivot_head_translation = Vector3(0, 7, 0)
  local pivot_head_rotation = Rotation(0, 0, 0)
  l_6_0.stances.default.steelsight.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_6_0.stances.default.steelsight.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_6_0.stances.default.steelsight.vel_overshot.yaw_neg = 4
  l_6_0.stances.default.steelsight.vel_overshot.yaw_pos = -4
  l_6_0.stances.default.steelsight.vel_overshot.pitch_neg = -2
  l_6_0.stances.default.steelsight.vel_overshot.pitch_pos = 2
  l_6_0.stances.default.steelsight.vel_overshot.pivot = pivot_shoulder_translation
  l_6_0.stances.default.steelsight.zoom_fov = true
  l_6_0.stances.default.steelsight.FOV = l_6_0.stances.default.standard.FOV
  l_6_0:_init_new_stances()
  l_6_0.movement_state = {}
  l_6_0.movement_state.standard = {}
  l_6_0.movement_state.standard.movement = {speed = {}, jump_velocity = {xy = {}}}
  l_6_0.movement_state.standard.movement.speed.STANDARD_MAX = 350
  l_6_0.movement_state.standard.movement.speed.RUNNING_MAX = 575
  l_6_0.movement_state.standard.movement.speed.CROUCHING_MAX = 225
  l_6_0.movement_state.standard.movement.speed.STEELSIGHT_MAX = 185
  l_6_0.movement_state.standard.movement.speed.INAIR_MAX = 185
  l_6_0.movement_state.standard.movement.jump_velocity.z = 470
  l_6_0.movement_state.standard.movement.jump_velocity.xy.run = l_6_0.movement_state.standard.movement.speed.RUNNING_MAX * 1
  l_6_0.movement_state.standard.movement.jump_velocity.xy.walk = l_6_0.movement_state.standard.movement.speed.STANDARD_MAX * 1.2000000476837
  l_6_0.movement_state.interaction_delay = 1.5
  l_6_0.movement_state.stamina = {}
  l_6_0.movement_state.stamina.STAMINA_INIT = 20
  l_6_0.movement_state.stamina.STAMINA_REGEN_RATE = 3
  l_6_0.movement_state.stamina.STAMINA_DRAIN_RATE = 2
  l_6_0.movement_state.stamina.REGENERATE_TIME = 1
  l_6_0.movement_state.stamina.MIN_STAMINA_THRESHOLD = 4
  l_6_0.movement_state.stamina.JUMP_STAMINA_DRAIN = 2
  l_6_0.camera = {}
  l_6_0.camera.MIN_SENSITIVITY = 0.30000001192093
  l_6_0.camera.MAX_SENSITIVITY = 1.7000000476837
end

PlayerTweakData._init_new_stances = function(l_7_0)
  l_7_0.stances.new_m4 = deep_clone(l_7_0.stances.default)
  local pivot_shoulder_translation = Vector3(10.728799819946, 23.012500762939, -1.8890999555588)
  local pivot_shoulder_rotation = Rotation(0.10660699754953, -0.084448598325253, 0.62919902801514)
  local pivot_head_translation = Vector3(7, 20, -0.5)
  local pivot_head_rotation = Rotation(0.40000000596046, 0.40000000596046, 0)
  l_7_0.stances.new_m4.standard.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.new_m4.standard.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.new_m4.standard.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -20, 0)
  l_7_0.stances.new_m4.steelsight.vel_overshot.pitch_neg = -17
  l_7_0.stances.new_m4.steelsight.vel_overshot.pitch_pos = 17
  local pivot_head_translation = Vector3(0, 10, 0)
  local pivot_head_rotation = Rotation(0, 0, 0)
  l_7_0.stances.new_m4.steelsight.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.new_m4.steelsight.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.new_m4.steelsight.FOV = l_7_0.stances.new_m4.standard.FOV
  l_7_0.stances.new_m4.steelsight.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -7, 0)
  l_7_0.stances.new_m4.steelsight.vel_overshot.yaw_neg = 8
  l_7_0.stances.new_m4.steelsight.vel_overshot.yaw_pos = -8
  l_7_0.stances.new_m4.steelsight.vel_overshot.pitch_neg = -17
  l_7_0.stances.new_m4.steelsight.vel_overshot.pitch_pos = 17
  local pivot_head_translation = Vector3(6, 16, -0.5)
  local pivot_head_rotation = Rotation(0.20000000298023, 0.20000000298023, 0)
  l_7_0.stances.new_m4.crouched.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.new_m4.crouched.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.new_m4.crouched.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -20, 0)
  l_7_0.stances.glock_18c = deep_clone(l_7_0.stances.default)
  local pivot_shoulder_translation = Vector3(8.4905099868774, 38.647399902344, -5.0939898490906)
  local pivot_shoulder_rotation = Rotation(0.099994897842407, -0.68770200014114, 0.63030397891998)
  local pivot_head_translation = Vector3(5, 36, -2)
  local pivot_head_rotation = Rotation(0, 0, 0)
  l_7_0.stances.glock_18c.standard.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.glock_18c.standard.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.glock_18c.standard.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -35, 0)
  l_7_0.stances.glock_18c.standard.vel_overshot.yaw_neg = 10
  l_7_0.stances.glock_18c.standard.vel_overshot.yaw_pos = -10
  l_7_0.stances.glock_18c.standard.vel_overshot.pitch_neg = -13
  l_7_0.stances.glock_18c.standard.vel_overshot.pitch_pos = 13
  local pivot_head_translation = Vector3(0, 37, 0)
  local pivot_head_rotation = Rotation(0, 0, 0)
  l_7_0.stances.glock_18c.steelsight.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.glock_18c.steelsight.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.glock_18c.steelsight.FOV = l_7_0.stances.glock_18c.standard.FOV
  l_7_0.stances.glock_18c.steelsight.zoom_fov = false
  l_7_0.stances.glock_18c.steelsight.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -40, 0)
  l_7_0.stances.glock_18c.steelsight.vel_overshot.yaw_neg = 8
  l_7_0.stances.glock_18c.steelsight.vel_overshot.yaw_pos = -8
  l_7_0.stances.glock_18c.steelsight.vel_overshot.pitch_neg = -8
  l_7_0.stances.glock_18c.steelsight.vel_overshot.pitch_pos = 8
  local pivot_head_translation = Vector3(3, 32, -2)
  local pivot_head_rotation = Rotation(0, 0, 0)
  l_7_0.stances.glock_18c.crouched.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.glock_18c.crouched.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.glock_18c.crouched.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -30, 0)
  l_7_0.stances.amcar = deep_clone(l_7_0.stances.default)
  local pivot_shoulder_translation = Vector3(10.733799934387, 23.013200759888, -1.4366999864578)
  local pivot_shoulder_rotation = Rotation(0.10662999749184, -0.084427699446678, 0.62921100854874)
  local pivot_head_translation = Vector3(7, 20, -0.5)
  local pivot_head_rotation = Rotation(0.40000000596046, 0.40000000596046, 0)
  l_7_0.stances.amcar.standard.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.amcar.standard.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.amcar.standard.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -20, 0)
  l_7_0.stances.amcar.standard.vel_overshot.yaw_neg = -6
  l_7_0.stances.amcar.standard.vel_overshot.yaw_pos = 6
  l_7_0.stances.amcar.standard.vel_overshot.pitch_neg = 5
  l_7_0.stances.amcar.standard.vel_overshot.pitch_pos = -5
  local pivot_head_translation = Vector3(0, 14, 0)
  local pivot_head_rotation = Rotation(0, 0, 0)
  l_7_0.stances.amcar.steelsight.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.amcar.steelsight.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.amcar.steelsight.FOV = l_7_0.stances.amcar.standard.FOV
  l_7_0.stances.amcar.steelsight.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -7, 0)
  l_7_0.stances.amcar.steelsight.vel_overshot.yaw_neg = -2
  l_7_0.stances.amcar.steelsight.vel_overshot.yaw_pos = 4
  l_7_0.stances.amcar.steelsight.vel_overshot.pitch_neg = 5
  l_7_0.stances.amcar.steelsight.vel_overshot.pitch_pos = -5
  local pivot_head_translation = Vector3(6, 20, -0.5)
  local pivot_head_rotation = Rotation(0.20000000298023, 0.20000000298023, 0)
  l_7_0.stances.amcar.crouched.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.amcar.crouched.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.amcar.crouched.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -20, 0)
  l_7_0.stances.amcar.crouched.vel_overshot.yaw_neg = -6
  l_7_0.stances.amcar.crouched.vel_overshot.yaw_pos = 6
  l_7_0.stances.amcar.crouched.vel_overshot.pitch_neg = 5
  l_7_0.stances.amcar.crouched.vel_overshot.pitch_pos = -5
  l_7_0.stances.m16 = deep_clone(l_7_0.stances.default)
  local pivot_shoulder_translation = Vector3(10.735300064087, 23.013900756836, -1.4355299472809)
  local pivot_shoulder_rotation = Rotation(0.10666500031948, -0.084510400891304, 0.62923097610474)
  local pivot_head_translation = Vector3(7, 20, -0.5)
  local pivot_head_rotation = Rotation(0.40000000596046, 0.40000000596046, 0)
  l_7_0.stances.m16.standard.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.m16.standard.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.m16.standard.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -15, 0)
  l_7_0.stances.m16.standard.vel_overshot.yaw_neg = -6
  l_7_0.stances.m16.standard.vel_overshot.yaw_pos = 6
  l_7_0.stances.m16.standard.vel_overshot.pitch_neg = 10
  l_7_0.stances.m16.standard.vel_overshot.pitch_pos = -10
  local pivot_head_translation = Vector3(0, 14, 0)
  local pivot_head_rotation = Rotation(0, 0, 0)
  l_7_0.stances.m16.steelsight.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.m16.steelsight.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.m16.steelsight.FOV = l_7_0.stances.m16.standard.FOV
  l_7_0.stances.m16.steelsight.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -7, 0)
  l_7_0.stances.m16.steelsight.vel_overshot.yaw_neg = -4
  l_7_0.stances.m16.steelsight.vel_overshot.yaw_pos = 4
  l_7_0.stances.m16.steelsight.vel_overshot.pitch_neg = 8
  l_7_0.stances.m16.steelsight.vel_overshot.pitch_pos = -8
  local pivot_head_translation = Vector3(6, 16, -0.5)
  local pivot_head_rotation = Rotation(0.20000000298023, 0.20000000298023, 0)
  l_7_0.stances.m16.crouched.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.m16.crouched.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.m16.crouched.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -15, 0)
  l_7_0.stances.m16.crouched.vel_overshot.yaw_neg = -4
  l_7_0.stances.m16.crouched.vel_overshot.yaw_pos = 4
  l_7_0.stances.m16.crouched.vel_overshot.pitch_neg = 8
  l_7_0.stances.m16.crouched.vel_overshot.pitch_pos = -8
  l_7_0.stances.olympic = deep_clone(l_7_0.stances.default)
  local pivot_shoulder_translation = Vector3(10.733499526978, 23.013000488281, -1.4365099668503)
  local pivot_shoulder_rotation = Rotation(0.10662599653006, -0.08337789773941, 0.62919002771378)
  local pivot_head_translation = Vector3(7, 20, -0.5)
  local pivot_head_rotation = Rotation(0.40000000596046, 0.40000000596046, 0)
  l_7_0.stances.olympic.standard.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.olympic.standard.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.olympic.standard.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -15, 0)
  local pivot_head_translation = Vector3(0, 14, 0)
  local pivot_head_rotation = Rotation(0, 0, 0)
  l_7_0.stances.olympic.steelsight.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.olympic.steelsight.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.olympic.steelsight.FOV = l_7_0.stances.olympic.standard.FOV
  l_7_0.stances.olympic.steelsight.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -7, 0)
  l_7_0.stances.olympic.steelsight.vel_overshot.yaw_neg = 8
  l_7_0.stances.olympic.steelsight.vel_overshot.yaw_pos = -8
  l_7_0.stances.olympic.steelsight.vel_overshot.pitch_neg = -17
  l_7_0.stances.olympic.steelsight.vel_overshot.pitch_pos = 17
  local pivot_head_translation = Vector3(6, 17, -0.5)
  local pivot_head_rotation = Rotation(0.20000000298023, 0.20000000298023, 0)
  l_7_0.stances.olympic.crouched.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.olympic.crouched.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.olympic.crouched.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -7, 0)
  l_7_0.stances.ak74 = deep_clone(l_7_0.stances.default)
  local pivot_shoulder_translation = Vector3(10.663499832153, 40.379501342773, -4.9326500892639)
  local pivot_shoulder_rotation = Rotation(0.10667999833822, -0.084495797753334, 0.6292279958725)
  local pivot_head_translation = Vector3(9, 36, -2)
  local pivot_head_rotation = Rotation(0.40000000596046, 0.40000000596046, 0)
  l_7_0.stances.ak74.standard.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.ak74.standard.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.ak74.standard.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -30, 0)
  l_7_0.stances.ak74.standard.vel_overshot.yaw_neg = -5
  l_7_0.stances.ak74.standard.vel_overshot.yaw_pos = 5
  l_7_0.stances.ak74.standard.vel_overshot.pitch_neg = 7
  l_7_0.stances.ak74.standard.vel_overshot.pitch_pos = -7
  local pivot_head_translation = Vector3(6, 36, -1)
  local pivot_head_rotation = Rotation(0.20000000298023, 0.20000000298023, 0)
  l_7_0.stances.ak74.crouched.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.ak74.crouched.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.ak74.crouched.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -30, 0)
  l_7_0.stances.ak74.crouched.vel_overshot.yaw_neg = -4
  l_7_0.stances.ak74.crouched.vel_overshot.yaw_pos = 4
  l_7_0.stances.ak74.crouched.vel_overshot.pitch_neg = 5
  l_7_0.stances.ak74.crouched.vel_overshot.pitch_pos = -5
  local pivot_head_translation = Vector3(0, 30, 0)
  local pivot_head_rotation = Rotation(0, 0, 0)
  l_7_0.stances.ak74.steelsight.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.ak74.steelsight.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.ak74.steelsight.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -30, 0)
  l_7_0.stances.ak74.steelsight.vel_overshot.yaw_neg = -4
  l_7_0.stances.ak74.steelsight.vel_overshot.yaw_pos = 4
  l_7_0.stances.ak74.steelsight.vel_overshot.pitch_neg = 5
  l_7_0.stances.ak74.steelsight.vel_overshot.pitch_pos = -5
  l_7_0.stances.akm = deep_clone(l_7_0.stances.default)
  local pivot_shoulder_translation = Vector3(10.667699813843, 40.388500213623, -4.9421601295471)
  local pivot_shoulder_rotation = Rotation(0.10664000362158, -0.084428496658802, 0.6292120218277)
  local pivot_head_translation = Vector3(9, 36, -2)
  local pivot_head_rotation = Rotation(0.40000000596046, 0.40000000596046, 0)
  l_7_0.stances.akm.standard.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.akm.standard.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.akm.standard.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -30, 0)
  l_7_0.stances.akm.standard.vel_overshot.yaw_neg = -5
  l_7_0.stances.akm.standard.vel_overshot.yaw_pos = 5
  l_7_0.stances.akm.standard.vel_overshot.pitch_neg = 7
  l_7_0.stances.akm.standard.vel_overshot.pitch_pos = -7
  local pivot_head_translation = Vector3(6, 36, -1)
  local pivot_head_rotation = Rotation(0.20000000298023, 0.20000000298023, 0)
  l_7_0.stances.akm.crouched.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.akm.crouched.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.akm.crouched.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -30, 0)
  l_7_0.stances.akm.crouched.vel_overshot.yaw_neg = -4
  l_7_0.stances.akm.crouched.vel_overshot.yaw_pos = 4
  l_7_0.stances.akm.crouched.vel_overshot.pitch_neg = 5
  l_7_0.stances.akm.crouched.vel_overshot.pitch_pos = -5
  local pivot_head_translation = Vector3(0, 30, 0)
  local pivot_head_rotation = Rotation(0, 0, 0)
  l_7_0.stances.akm.steelsight.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.akm.steelsight.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.akm.steelsight.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -30, 0)
  l_7_0.stances.akm.steelsight.vel_overshot.yaw_neg = -4
  l_7_0.stances.akm.steelsight.vel_overshot.yaw_pos = 4
  l_7_0.stances.akm.steelsight.vel_overshot.pitch_neg = 5
  l_7_0.stances.akm.steelsight.vel_overshot.pitch_pos = -5
  l_7_0.stances.akmsu = deep_clone(l_7_0.stances.default)
  local pivot_shoulder_translation = Vector3(10.664600372314, 40.37850189209, -4.6755399703979)
  local pivot_shoulder_rotation = Rotation(0.10633999854326, -0.085468597710133, 0.62892800569534)
  local pivot_head_translation = Vector3(8, 36, -2)
  local pivot_head_rotation = Rotation(0.40000000596046, 0.40000000596046, 0)
  l_7_0.stances.akmsu.standard.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.akmsu.standard.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.akmsu.standard.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -30, 0)
  l_7_0.stances.akmsu.standard.vel_overshot.yaw_neg = 10
  l_7_0.stances.akmsu.standard.vel_overshot.yaw_pos = -10
  l_7_0.stances.akmsu.standard.vel_overshot.pitch_neg = -20
  l_7_0.stances.akmsu.standard.vel_overshot.pitch_pos = 20
  local pivot_head_translation = Vector3(6, 36, -1)
  local pivot_head_rotation = Rotation(0.20000000298023, 0.20000000298023, 0)
  l_7_0.stances.akmsu.crouched.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.akmsu.crouched.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.akmsu.crouched.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -30, 0)
  local pivot_head_translation = Vector3(0, 30, 0)
  local pivot_head_rotation = Rotation(0, 0, 0)
  l_7_0.stances.akmsu.steelsight.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.akmsu.steelsight.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.akmsu.steelsight.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -30, 0)
  l_7_0.stances.akmsu.steelsight.vel_overshot.yaw_neg = 10
  l_7_0.stances.akmsu.steelsight.vel_overshot.yaw_pos = -10
  l_7_0.stances.akmsu.steelsight.vel_overshot.pitch_neg = -20
  l_7_0.stances.akmsu.steelsight.vel_overshot.pitch_pos = 20
  l_7_0.stances.saiga = deep_clone(l_7_0.stances.default)
  local pivot_shoulder_translation = Vector3(10.663000106812, 40.375400543213, -4.9361901283264)
  local pivot_shoulder_rotation = Rotation(0.10661400109529, -0.084447100758553, 0.62919700145721)
  local pivot_head_translation = Vector3(9, 36, -2)
  local pivot_head_rotation = Rotation(0.40000000596046, 0.40000000596046, 0)
  l_7_0.stances.saiga.standard.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.saiga.standard.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.saiga.standard.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -30, 0)
  local pivot_head_translation = Vector3(6, 36, -1)
  local pivot_head_rotation = Rotation(0.20000000298023, 0.20000000298023, 0)
  l_7_0.stances.saiga.crouched.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.saiga.crouched.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.saiga.crouched.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -30, 0)
  local pivot_head_translation = Vector3(0, 30, 0)
  local pivot_head_rotation = Rotation(0, 0, 0)
  l_7_0.stances.saiga.steelsight.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.saiga.steelsight.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.saiga.steelsight.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -30, 0)
  l_7_0.stances.saiga.steelsight.vel_overshot.yaw_neg = 10
  l_7_0.stances.saiga.steelsight.vel_overshot.yaw_pos = -10
  l_7_0.stances.saiga.steelsight.vel_overshot.pitch_neg = -20
  l_7_0.stances.saiga.steelsight.vel_overshot.pitch_pos = 20
  l_7_0.stances.ak5 = deep_clone(l_7_0.stances.default)
  local pivot_shoulder_translation = Vector3(10.733200073242, 15.614500045776, -2.755490064621)
  local pivot_shoulder_rotation = Rotation(0.10662499815226, -0.43099701404572, 0.6292120218277)
  local pivot_head_translation = Vector3(8, 16, -2)
  local pivot_head_rotation = Rotation(0.40000000596046, 0.40000000596046, 0)
  l_7_0.stances.ak5.standard.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.ak5.standard.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.ak5.standard.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -20, 0)
  l_7_0.stances.ak5.standard.vel_overshot.yaw_neg = 10
  l_7_0.stances.ak5.standard.vel_overshot.yaw_pos = -10
  l_7_0.stances.ak5.standard.vel_overshot.pitch_neg = -10
  l_7_0.stances.ak5.standard.vel_overshot.pitch_pos = 10
  local pivot_head_translation = Vector3(0, 18, 0)
  local pivot_head_rotation = Rotation(0, 0, 0)
  l_7_0.stances.ak5.steelsight.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.ak5.steelsight.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.ak5.steelsight.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -10, 0)
  l_7_0.stances.ak5.steelsight.vel_overshot.yaw_neg = 4
  l_7_0.stances.ak5.steelsight.vel_overshot.yaw_pos = -4
  l_7_0.stances.ak5.steelsight.vel_overshot.pitch_neg = -17
  l_7_0.stances.ak5.steelsight.vel_overshot.pitch_pos = 17
  local pivot_head_translation = Vector3(7, 15, -0.5)
  local pivot_head_rotation = Rotation(0.20000000298023, 0.20000000298023, 0)
  l_7_0.stances.ak5.crouched.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.ak5.crouched.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.ak5.crouched.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -30, 0)
  l_7_0.stances.aug = deep_clone(l_7_0.stances.default)
  local pivot_shoulder_translation = Vector3(10.704600334167, 17.149900436401, -5.2119297981262)
  local pivot_shoulder_rotation = Rotation(0.10636200010777, -0.085595600306988, 0.62896198034286)
  local pivot_head_translation = Vector3(7, 20, -1)
  local pivot_head_rotation = Rotation(0, 0, 0)
  l_7_0.stances.aug.standard.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.aug.standard.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.aug.standard.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -20, 0)
  l_7_0.stances.aug.standard.vel_overshot.yaw_neg = 8
  l_7_0.stances.aug.standard.vel_overshot.yaw_pos = -8
  l_7_0.stances.aug.standard.vel_overshot.pitch_neg = -10
  l_7_0.stances.aug.standard.vel_overshot.pitch_pos = 10
  local pivot_head_translation = Vector3(0, 17, 0)
  local pivot_head_rotation = Rotation(0, 0, 0)
  l_7_0.stances.aug.steelsight.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.aug.steelsight.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.aug.steelsight.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -20, 0)
  l_7_0.stances.aug.steelsight.vel_overshot.yaw_neg = 4
  l_7_0.stances.aug.steelsight.vel_overshot.yaw_pos = -4
  l_7_0.stances.aug.steelsight.vel_overshot.pitch_neg = -17
  l_7_0.stances.aug.steelsight.vel_overshot.pitch_pos = 17
  local pivot_head_translation = Vector3(4, 18, 0)
  local pivot_head_rotation = Rotation(0, 0, 0)
  l_7_0.stances.aug.crouched.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.aug.crouched.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.aug.crouched.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -20, 0)
  l_7_0.stances.g36 = deep_clone(l_7_0.stances.default)
  local pivot_shoulder_translation = Vector3(10.565799713135, 24.876800537109, -1.0792299509048)
  local pivot_shoulder_rotation = Rotation(-0.00031374598620459, 0.00081396702444181, -0.00027677998878062)
  local pivot_head_translation = Vector3(9, 18, 0)
  local pivot_head_rotation = Rotation(0.40000000596046, 0.40000000596046, 0)
  l_7_0.stances.g36.standard.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.g36.standard.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.g36.standard.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -25, 0)
  local pivot_head_translation = Vector3(0, 17, 0)
  local pivot_head_rotation = Rotation(0, 0, 0)
  l_7_0.stances.g36.steelsight.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.g36.steelsight.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.g36.steelsight.FOV = l_7_0.stances.g36.standard.FOV
  l_7_0.stances.g36.steelsight.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -10, 0)
  l_7_0.stances.g36.steelsight.vel_overshot.yaw_neg = 5
  l_7_0.stances.g36.steelsight.vel_overshot.yaw_pos = -5
  l_7_0.stances.g36.steelsight.vel_overshot.pitch_neg = -17
  l_7_0.stances.g36.steelsight.vel_overshot.pitch_pos = 17
  local pivot_head_translation = Vector3(6, 17, 1)
  local pivot_head_rotation = Rotation(0.20000000298023, 0.20000000298023, 0)
  l_7_0.stances.g36.crouched.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.g36.crouched.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.g36.crouched.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -25, 0)
  l_7_0.stances.p90 = deep_clone(l_7_0.stances.default)
  local pivot_shoulder_translation = Vector3(11.000200271606, 24.329299926758, -0.96264100074768)
  local pivot_shoulder_rotation = Rotation(0.21278999745846, 0.97021400928497, 0.19787700474262)
  local pivot_head_translation = Vector3(7, 23, 0)
  local pivot_head_rotation = Rotation(0, 0, -1)
  l_7_0.stances.p90.standard.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.p90.standard.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.p90.standard.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -25, 0)
  l_7_0.stances.p90.standard.vel_overshot.yaw_neg = 10
  l_7_0.stances.p90.standard.vel_overshot.yaw_pos = -10
  l_7_0.stances.p90.standard.vel_overshot.pitch_neg = -15
  l_7_0.stances.p90.standard.vel_overshot.pitch_pos = 15
  local pivot_head_translation = Vector3(0, 20, 0)
  local pivot_head_rotation = Rotation(0, 0, -0.5)
  l_7_0.stances.p90.steelsight.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.p90.steelsight.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.p90.steelsight.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -15, 0)
  l_7_0.stances.p90.steelsight.vel_overshot.yaw_neg = 5
  l_7_0.stances.p90.steelsight.vel_overshot.yaw_pos = -5
  l_7_0.stances.p90.steelsight.vel_overshot.pitch_neg = -17
  l_7_0.stances.p90.steelsight.vel_overshot.pitch_pos = 17
  local pivot_head_translation = Vector3(6, 19, 3)
  local pivot_head_rotation = Rotation(0, 0, 0)
  l_7_0.stances.p90.crouched.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.p90.crouched.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.p90.crouched.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -25, 0)
  l_7_0.stances.new_m14 = deep_clone(l_7_0.stances.default)
  local pivot_shoulder_translation = Vector3(10.703700065613, 23.03039932251, -4.446310043335)
  local pivot_shoulder_rotation = Rotation(0.10662999749184, -0.08444319665432, 0.62919700145721)
  local pivot_head_translation = Vector3(6, 18, -2)
  local pivot_head_rotation = Rotation(0, 0, 0)
  l_7_0.stances.new_m14.standard.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.new_m14.standard.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.new_m14.standard.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -12, 0)
  l_7_0.stances.new_m14.standard.vel_overshot.yaw_neg = -5
  l_7_0.stances.new_m14.standard.vel_overshot.yaw_pos = 5
  l_7_0.stances.new_m14.standard.vel_overshot.pitch_neg = 5
  l_7_0.stances.new_m14.standard.vel_overshot.pitch_pos = -5
  local pivot_head_translation = Vector3(0, 10, 0)
  local pivot_head_rotation = Rotation(0, 0, 0)
  l_7_0.stances.new_m14.steelsight.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.new_m14.steelsight.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.new_m14.steelsight.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -5, 0)
  l_7_0.stances.new_m14.steelsight.vel_overshot.yaw_neg = -4
  l_7_0.stances.new_m14.steelsight.vel_overshot.yaw_pos = 4
  l_7_0.stances.new_m14.steelsight.vel_overshot.pitch_neg = 3
  l_7_0.stances.new_m14.steelsight.vel_overshot.pitch_pos = -3
  local pivot_head_translation = Vector3(5, 18, 0)
  local pivot_head_rotation = Rotation(0, 0, 0)
  l_7_0.stances.new_m14.crouched.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.new_m14.crouched.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.new_m14.crouched.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -12, 0)
  l_7_0.stances.new_m14.crouched.vel_overshot.yaw_neg = -6
  l_7_0.stances.new_m14.crouched.vel_overshot.yaw_pos = 6
  l_7_0.stances.new_m14.crouched.vel_overshot.pitch_neg = 4
  l_7_0.stances.new_m14.crouched.vel_overshot.pitch_pos = -4
  l_7_0.stances.mp9 = deep_clone(l_7_0.stances.default)
  local pivot_shoulder_translation = Vector3(8.6442699432373, 34.770198822021, -4.7661700248718)
  local pivot_shoulder_rotation = Rotation(0.10999800264835, 0.012308100238442, 0.63029497861862)
  local pivot_head_translation = Vector3(8, 23, -2)
  local pivot_head_rotation = Rotation(0, 0, 0)
  l_7_0.stances.mp9.standard.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.mp9.standard.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.mp9.standard.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -15, 0)
  l_7_0.stances.mp9.standard.vel_overshot.yaw_neg = 10
  l_7_0.stances.mp9.standard.vel_overshot.yaw_pos = -10
  l_7_0.stances.mp9.standard.vel_overshot.pitch_neg = -5
  l_7_0.stances.mp9.standard.vel_overshot.pitch_pos = 5
  local pivot_head_translation = Vector3(0, 22, 0)
  local pivot_head_rotation = Rotation(0, 0, 0)
  l_7_0.stances.mp9.steelsight.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.mp9.steelsight.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.mp9.steelsight.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -5, 0)
  l_7_0.stances.mp9.steelsight.vel_overshot.yaw_neg = 4
  l_7_0.stances.mp9.steelsight.vel_overshot.yaw_pos = -4
  l_7_0.stances.mp9.steelsight.vel_overshot.pitch_neg = -8
  l_7_0.stances.mp9.steelsight.vel_overshot.pitch_pos = 8
  local pivot_head_translation = Vector3(7, 20, 0)
  local pivot_head_rotation = Rotation(0, 0, 0)
  l_7_0.stances.mp9.crouched.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.mp9.crouched.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.mp9.crouched.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -15, 0)
  l_7_0.stances.deagle = deep_clone(l_7_0.stances.default)
  local pivot_shoulder_translation = Vector3(8.5174398422241, 40.648899078369, -2.6693398952484)
  local pivot_shoulder_rotation = Rotation(0.10000800341368, -0.68769800662994, 0.63028901815414)
  local pivot_head_translation = Vector3(5, 35, -2)
  local pivot_head_rotation = Rotation(0, 0, 0)
  l_7_0.stances.deagle.standard.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.deagle.standard.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.deagle.standard.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -20, 0)
  l_7_0.stances.deagle.standard.vel_overshot.yaw_neg = -5
  l_7_0.stances.deagle.standard.vel_overshot.yaw_pos = 5
  l_7_0.stances.deagle.standard.vel_overshot.pitch_neg = 4
  l_7_0.stances.deagle.standard.vel_overshot.pitch_pos = -4
  local pivot_head_translation = Vector3(0, 35, 0)
  local pivot_head_rotation = Rotation(0, 0, 0)
  l_7_0.stances.deagle.steelsight.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.deagle.steelsight.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.deagle.steelsight.zoom_fov = false
  l_7_0.stances.deagle.steelsight.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -30, 0)
  l_7_0.stances.deagle.steelsight.vel_overshot.yaw_neg = -4
  l_7_0.stances.deagle.steelsight.vel_overshot.yaw_pos = 2
  l_7_0.stances.deagle.steelsight.vel_overshot.pitch_neg = 2
  l_7_0.stances.deagle.steelsight.vel_overshot.pitch_pos = -2
  local pivot_head_translation = Vector3(4, 36, -2)
  local pivot_head_rotation = Rotation(0, 0, 0)
  l_7_0.stances.deagle.crouched.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.deagle.crouched.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.deagle.crouched.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -20, 0)
  l_7_0.stances.new_mp5 = deep_clone(l_7_0.stances.default)
  local pivot_shoulder_translation = Vector3(10.741399765015, 18.454299926758, -3.2917499542236)
  local pivot_shoulder_rotation = Rotation(0.10693400353193, -0.22001500427723, 0.62972897291183)
  local pivot_head_translation = Vector3(8, 14, -2)
  local pivot_head_rotation = Rotation(0, 0, 0)
  l_7_0.stances.new_mp5.standard.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.new_mp5.standard.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.new_mp5.standard.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -10, 0)
  l_7_0.stances.new_mp5.standard.vel_overshot.yaw_neg = 10
  l_7_0.stances.new_mp5.standard.vel_overshot.yaw_pos = -10
  l_7_0.stances.new_mp5.standard.vel_overshot.pitch_neg = -5
  l_7_0.stances.new_mp5.standard.vel_overshot.pitch_pos = 5
  local pivot_head_translation = Vector3(0, 10, 0)
  local pivot_head_rotation = Rotation(0, 0, 0)
  l_7_0.stances.new_mp5.steelsight.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.new_mp5.steelsight.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.new_mp5.steelsight.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -5, 0)
  l_7_0.stances.new_mp5.steelsight.vel_overshot.yaw_neg = 4
  l_7_0.stances.new_mp5.steelsight.vel_overshot.yaw_pos = -4
  l_7_0.stances.new_mp5.steelsight.vel_overshot.pitch_neg = -8
  l_7_0.stances.new_mp5.steelsight.vel_overshot.pitch_pos = 8
  local pivot_head_translation = Vector3(7, 15, -0.5)
  local pivot_head_rotation = Rotation(0, 0, 0)
  l_7_0.stances.new_mp5.crouched.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.new_mp5.crouched.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.new_mp5.crouched.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -10, 0)
  l_7_0.stances.colt_1911 = deep_clone(l_7_0.stances.default)
  local pivot_shoulder_translation = Vector3(8.5107202529907, 41.182300567627, -3.1959199905396)
  local pivot_shoulder_rotation = Rotation(0.099982500076294, -0.6885290145874, 0.63029599189758)
  local pivot_head_translation = Vector3(5, 38, -2)
  local pivot_head_rotation = Rotation(0, 0, 0)
  l_7_0.stances.colt_1911.standard.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.colt_1911.standard.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.colt_1911.standard.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -30, 0)
  l_7_0.stances.colt_1911.standard.vel_overshot.yaw_neg = 10
  l_7_0.stances.colt_1911.standard.vel_overshot.yaw_pos = -10
  l_7_0.stances.colt_1911.standard.vel_overshot.pitch_neg = -8
  l_7_0.stances.colt_1911.standard.vel_overshot.pitch_pos = 8
  local pivot_head_translation = Vector3(0, 42, 0)
  local pivot_head_rotation = Rotation(0, 0, 0)
  l_7_0.stances.colt_1911.steelsight.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.colt_1911.steelsight.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.colt_1911.steelsight.zoom_fov = false
  l_7_0.stances.colt_1911.steelsight.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -30, 0)
  l_7_0.stances.colt_1911.steelsight.vel_overshot.yaw_neg = 8
  l_7_0.stances.colt_1911.steelsight.vel_overshot.yaw_pos = -8
  l_7_0.stances.colt_1911.steelsight.vel_overshot.pitch_neg = -12
  l_7_0.stances.colt_1911.steelsight.vel_overshot.pitch_pos = 12
  local pivot_head_translation = Vector3(4, 35, -2)
  local pivot_head_rotation = Rotation(0, 0, 0)
  l_7_0.stances.colt_1911.crouched.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.colt_1911.crouched.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.colt_1911.crouched.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -20, 0)
  l_7_0.stances.mac10 = deep_clone(l_7_0.stances.default)
  local pivot_shoulder_translation = Vector3(8.6692895889282, 32.893398284912, -2.844330072403)
  local pivot_shoulder_rotation = Rotation(0.11000300198793, -0.8985750079155, 0.63029301166534)
  local pivot_head_translation = Vector3(8, 25, -2)
  local pivot_head_rotation = Rotation(0, 0, 0)
  l_7_0.stances.mac10.standard.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.mac10.standard.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.mac10.standard.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -20, 0)
  l_7_0.stances.mac10.standard.vel_overshot.yaw_neg = 15
  l_7_0.stances.mac10.standard.vel_overshot.yaw_pos = -15
  l_7_0.stances.mac10.standard.vel_overshot.pitch_neg = -15
  l_7_0.stances.mac10.standard.vel_overshot.pitch_pos = 15
  local pivot_head_translation = Vector3(0, 23, 0)
  local pivot_head_rotation = Rotation(0, 0, 0)
  l_7_0.stances.mac10.steelsight.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.mac10.steelsight.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.mac10.steelsight.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -15, 0)
  l_7_0.stances.mac10.steelsight.vel_overshot.yaw_neg = 15
  l_7_0.stances.mac10.steelsight.vel_overshot.yaw_pos = -15
  l_7_0.stances.mac10.steelsight.vel_overshot.pitch_neg = -18
  l_7_0.stances.mac10.steelsight.vel_overshot.pitch_pos = 18
  local pivot_head_translation = Vector3(7, 20, 0)
  local pivot_head_rotation = Rotation(0, 0, 0)
  l_7_0.stances.mac10.crouched.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.mac10.crouched.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.mac10.crouched.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -20, 0)
  l_7_0.stances.r870 = deep_clone(l_7_0.stances.default)
  local pivot_shoulder_translation = Vector3(10.736200332642, 12.888580322266, -4.2956800460815)
  local pivot_shoulder_rotation = Rotation(0.10661800205708, -0.084441497921944, 0.62920498847961)
  local pivot_head_translation = Vector3(5, 15, -1)
  local pivot_head_rotation = Rotation(0, 0, 0)
  l_7_0.stances.r870.standard.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.r870.standard.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.r870.standard.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -30, 0)
  l_7_0.stances.r870.standard.vel_overshot.yaw_neg = -5
  l_7_0.stances.r870.standard.vel_overshot.yaw_pos = 3
  l_7_0.stances.r870.standard.vel_overshot.pitch_neg = 2
  l_7_0.stances.r870.standard.vel_overshot.pitch_pos = -3
  local pivot_head_translation = Vector3(0, 15, 0)
  local pivot_head_rotation = Rotation(0, 0, 0)
  l_7_0.stances.r870.steelsight.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.r870.steelsight.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.r870.steelsight.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -30, 0)
  l_7_0.stances.r870.steelsight.vel_overshot.yaw_neg = -3
  l_7_0.stances.r870.steelsight.vel_overshot.yaw_pos = 3
  l_7_0.stances.r870.steelsight.vel_overshot.pitch_neg = 2
  l_7_0.stances.r870.steelsight.vel_overshot.pitch_pos = -2
  local pivot_head_translation = Vector3(4, 17, -2)
  local pivot_head_rotation = Rotation(-2, -2, 0)
  l_7_0.stances.r870.crouched.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.r870.crouched.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.r870.crouched.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -30, 0)
  l_7_0.stances.glock_17 = deep_clone(l_7_0.stances.default)
  local pivot_shoulder_translation = Vector3(8.4858198165894, 38.772701263428, -5.493579864502)
  local pivot_shoulder_rotation = Rotation(0.1000069975853, -0.68769198656082, 0.63029098510742)
  local pivot_head_translation = Vector3(5, 34, -2)
  local pivot_head_rotation = Rotation(0, 0, 0)
  l_7_0.stances.glock_17.standard.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.glock_17.standard.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.glock_17.standard.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -35, 0)
  l_7_0.stances.glock_17.standard.vel_overshot.yaw_neg = 10
  l_7_0.stances.glock_17.standard.vel_overshot.yaw_pos = -10
  l_7_0.stances.glock_17.standard.vel_overshot.pitch_neg = -13
  l_7_0.stances.glock_17.standard.vel_overshot.pitch_pos = 13
  local pivot_head_translation = Vector3(0, 35, 0)
  local pivot_head_rotation = Rotation(0, 0, 0)
  l_7_0.stances.glock_17.steelsight.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.glock_17.steelsight.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.glock_17.steelsight.FOV = l_7_0.stances.glock_17.standard.FOV
  l_7_0.stances.glock_17.steelsight.zoom_fov = false
  l_7_0.stances.glock_17.steelsight.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -35, 0)
  l_7_0.stances.glock_17.steelsight.vel_overshot.yaw_neg = 8
  l_7_0.stances.glock_17.steelsight.vel_overshot.yaw_pos = -8
  l_7_0.stances.glock_17.steelsight.vel_overshot.pitch_neg = -8
  l_7_0.stances.glock_17.steelsight.vel_overshot.pitch_pos = 8
  local pivot_head_translation = Vector3(4, 32, -2)
  local pivot_head_rotation = Rotation(0, 0, 0)
  l_7_0.stances.glock_17.crouched.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.glock_17.crouched.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.glock_17.crouched.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -35, 0)
  l_7_0.stances.huntsman = deep_clone(l_7_0.stances.default)
  local pivot_shoulder_translation = Vector3(10.656200408936, 32.971500396729, -6.7327899932861)
  local pivot_shoulder_rotation = Rotation(0.10666699707508, -0.084487602114677, 0.62922298908234)
  local pivot_head_translation = Vector3(6, 25, -2)
  local pivot_head_rotation = Rotation(0, 0, 0)
  l_7_0.stances.huntsman.standard.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.huntsman.standard.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.huntsman.standard.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -20, 0)
  local pivot_head_translation = Vector3(0, 20, -2)
  local pivot_head_rotation = Rotation(0, 2, 0)
  l_7_0.stances.huntsman.steelsight.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.huntsman.steelsight.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.huntsman.steelsight.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -20, 0)
  l_7_0.stances.huntsman.steelsight.vel_overshot.yaw_neg = 12
  l_7_0.stances.huntsman.steelsight.vel_overshot.yaw_pos = -12
  l_7_0.stances.huntsman.steelsight.vel_overshot.pitch_neg = -12
  l_7_0.stances.huntsman.steelsight.vel_overshot.pitch_pos = 12
  local pivot_head_translation = Vector3(4, 17, -2)
  local pivot_head_rotation = Rotation(-2, -2, 0)
  l_7_0.stances.huntsman.crouched.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.huntsman.crouched.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.huntsman.crouched.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -30, 0)
  l_7_0.stances.b92fs = deep_clone(l_7_0.stances.default)
  local pivot_shoulder_translation = Vector3(8.5007495880127, 40.922698974609, -4.1532797813416)
  local pivot_shoulder_rotation = Rotation(0.099399998784065, -0.68785101175308, 0.63004702329636)
  local pivot_head_translation = Vector3(5, 34, -2)
  local pivot_head_rotation = Rotation(0, 0, 0)
  l_7_0.stances.b92fs.standard.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.b92fs.standard.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.b92fs.standard.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -36, 0)
  local pivot_head_translation = Vector3(0, 37, 0)
  local pivot_head_rotation = Rotation(0, 0, 0)
  l_7_0.stances.b92fs.steelsight.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.b92fs.steelsight.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.b92fs.steelsight.zoom_fov = false
  l_7_0.stances.b92fs.steelsight.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -36, 0)
  l_7_0.stances.b92fs.steelsight.vel_overshot.yaw_neg = 5
  l_7_0.stances.b92fs.steelsight.vel_overshot.yaw_pos = -5
  l_7_0.stances.b92fs.steelsight.vel_overshot.pitch_neg = -12
  l_7_0.stances.b92fs.steelsight.vel_overshot.pitch_pos = 12
  local pivot_head_translation = Vector3(3, 32, -2)
  local pivot_head_rotation = Rotation(0, 0, 0)
  l_7_0.stances.b92fs.crouched.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.b92fs.crouched.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.b92fs.crouched.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -36, 0)
  l_7_0.stances.new_raging_bull = deep_clone(l_7_0.stances.default)
  local pivot_shoulder_translation = Vector3(8.4883403778076, 43.861198425293, -2.1936600208282)
  local pivot_shoulder_rotation = Rotation(0.099987097084522, -0.6871600151062, 0.62991899251938)
  local pivot_head_translation = Vector3(5, 30, -1)
  local pivot_head_rotation = Rotation(0, 0, 0)
  l_7_0.stances.new_raging_bull.standard.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.new_raging_bull.standard.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.new_raging_bull.standard.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -10, 0)
  l_7_0.stances.new_raging_bull.standard.vel_overshot.yaw_neg = -5
  l_7_0.stances.new_raging_bull.standard.vel_overshot.yaw_pos = 2
  l_7_0.stances.new_raging_bull.standard.vel_overshot.pitch_neg = 5
  l_7_0.stances.new_raging_bull.standard.vel_overshot.pitch_pos = -5
  local pivot_head_translation = Vector3(0, 36, 0)
  local pivot_head_rotation = Rotation(0, 0, 0)
  l_7_0.stances.new_raging_bull.steelsight.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.new_raging_bull.steelsight.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.new_raging_bull.steelsight.zoom_fov = false
  l_7_0.stances.new_raging_bull.steelsight.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -35, 0)
  l_7_0.stances.new_raging_bull.steelsight.vel_overshot.yaw_neg = -5
  l_7_0.stances.new_raging_bull.steelsight.vel_overshot.yaw_pos = 2
  l_7_0.stances.new_raging_bull.steelsight.vel_overshot.pitch_neg = 5
  l_7_0.stances.new_raging_bull.steelsight.vel_overshot.pitch_pos = -5
  local pivot_head_translation = Vector3(4, 33, -1)
  local pivot_head_rotation = Rotation(0, 0, 0)
  l_7_0.stances.new_raging_bull.crouched.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_7_0.stances.new_raging_bull.crouched.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_7_0.stances.new_raging_bull.crouched.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -30, 0)
  l_7_0:_init_saw()
  l_7_0:_init_serbu()
end

PlayerTweakData._init_saw = function(l_8_0)
  l_8_0.stances.saw = deep_clone(l_8_0.stances.default)
  local pivot_shoulder_translation = Vector3(10.709899902344, 18.432399749756, -4.3849301338196)
  local pivot_shoulder_rotation = Rotation(0.10662200301886, -0.21845200657845, 0.62919098138809)
  local pivot_head_translation = Vector3(10, 5, -5)
  local pivot_head_rotation = Rotation(0, 0, 0)
  l_8_0.stances.saw.standard.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_8_0.stances.saw.standard.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_8_0.stances.saw.standard.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -35, 0)
  l_8_0.stances.saw.standard.vel_overshot.yaw_neg = -15
  l_8_0.stances.saw.standard.vel_overshot.yaw_pos = 15
  l_8_0.stances.saw.standard.vel_overshot.pitch_neg = 15
  l_8_0.stances.saw.standard.vel_overshot.pitch_pos = -15
  local pivot_head_translation = Vector3(10, 10, -5)
  local pivot_head_rotation = Rotation(0, 0, 5)
  l_8_0.stances.saw.steelsight.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_8_0.stances.saw.steelsight.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_8_0.stances.saw.steelsight.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -35, 0)
  l_8_0.stances.saw.steelsight.zoom_fov = false
  l_8_0.stances.saw.steelsight.vel_overshot.yaw_neg = -15
  l_8_0.stances.saw.steelsight.vel_overshot.yaw_pos = 15
  l_8_0.stances.saw.steelsight.vel_overshot.pitch_neg = 15
  l_8_0.stances.saw.steelsight.vel_overshot.pitch_pos = -15
  local pivot_head_translation = Vector3(11, 5, -2)
  local pivot_head_rotation = Rotation(0, 0, 2)
  l_8_0.stances.saw.crouched.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_8_0.stances.saw.crouched.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_8_0.stances.saw.crouched.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -35, 0)
end

PlayerTweakData._init_serbu = function(l_9_0)
  l_9_0.stances.serbu = deep_clone(l_9_0.stances.default)
  local pivot_shoulder_translation = Vector3(10.710000038147, 18.703500747681, -4.302179813385)
  local pivot_shoulder_rotation = Rotation(0.10683800280094, -0.084469199180603, 0.6292729973793)
  local pivot_head_translation = Vector3(5, 20, -1)
  local pivot_head_rotation = Rotation(0, 0, 0)
  l_9_0.stances.serbu.standard.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_9_0.stances.serbu.standard.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_9_0.stances.serbu.standard.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -20, 0)
  l_9_0.stances.serbu.standard.vel_overshot.yaw_neg = 6
  l_9_0.stances.serbu.standard.vel_overshot.yaw_pos = -6
  l_9_0.stances.serbu.standard.vel_overshot.pitch_neg = -4
  l_9_0.stances.serbu.standard.vel_overshot.pitch_pos = 4
  local pivot_head_translation = Vector3(0, 20, 0)
  local pivot_head_rotation = Rotation(0, 0, 0)
  l_9_0.stances.serbu.steelsight.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_9_0.stances.serbu.steelsight.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_9_0.stances.serbu.steelsight.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -10, 0)
  l_9_0.stances.serbu.steelsight.vel_overshot.yaw_neg = 5
  l_9_0.stances.serbu.steelsight.vel_overshot.yaw_pos = -4
  l_9_0.stances.serbu.steelsight.vel_overshot.pitch_neg = -5
  l_9_0.stances.serbu.steelsight.vel_overshot.pitch_pos = 5
  local pivot_head_translation = Vector3(4, 17, -2)
  local pivot_head_rotation = Rotation(-2, -2, 0)
  l_9_0.stances.serbu.crouched.shoulders.translation = pivot_head_translation - pivot_shoulder_translation:rotate_with(pivot_shoulder_rotation:inverse()):rotate_with(pivot_head_rotation)
  l_9_0.stances.serbu.crouched.shoulders.rotation = pivot_head_rotation * pivot_shoulder_rotation:inverse()
  l_9_0.stances.serbu.crouched.vel_overshot.pivot = pivot_shoulder_translation + Vector3(0, -20, 0)
end


